// react-demo/src/components/pagination/examples/pagination-combined-example.jsx
import { useRef, useEffect } from "react";
import { VegaPagination } from "@heartlandone/vega-react";

const App = () => {
  const recordsPagination = useRef();
  useEffect(() => {
    recordsPagination.current.extensions = [
      ["currentPageLabel", "pageSizeSelector"],
      ["pageSelector", "goTo"],
    ];
  });
  return (
    <VegaPagination
      ref={recordsPagination}
      current={1}
      pageSize={10}
      total={100}
    />
  );
};
export default App;

// vue-demo/src/components/pagination/examples/pagination-combined-example.vue
<script>
import { VegaPagination } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaPagination },
  mounted() {
    this.$refs.recordsPagination.$el.extensions = [
      ["currentPageLabel", "pageSizeSelector"],
      ["pageSelector", "goTo"]
    ]
  }
}
</script>
<template>
  <VegaPagination
    ref="recordsPagination"
    :current="1"
    :page-size="10"
    :total="100"
  />
</template>
