// react-demo/src/components/page-notification/examples/page-notification-with-actions.jsx
import { VegaFlex, VegaButton } from "@heartlandone/vega-react";

const App = () => {
  const openNotifyWithAction = async () => {
    const id = await window.VegaNotify.open({
      title: "Title",
      duration: 0,
      message:
        "This notification will not be closed, because the duration is set 0",
      actionButtons: [
        {
          label: "Confirm",
          onVegaClick: () => {
            window.VegaNotify.close(id);
          },
        },
      ],
    });
  };
  const openNotifyWithActions = async () => {
    const id = await window.VegaNotify.open({
      title: "Title",
      duration: 10000,
      message: `This notification will close after 10s`,
      actionButtons: [
        {
          label: "Cancel",
          onVegaClick: () => {
            window.VegaNotify.close(id);
          },
        },
        {
          label: "OK",
          onVegaClick: () => {
            window.VegaNotify.close(id);
          },
        },
      ],
    });
  };
  return (
    <VegaFlex gap={`size-16`}>
      <VegaButton onVegaClick={openNotifyWithAction}>With action</VegaButton>
      <VegaButton variant={`secondary`} onVegaClick={openNotifyWithActions}>
        With actions
      </VegaButton>
    </VegaFlex>
  );
};

export default App;

// angular-demo/src/components/page-notification/examples/page-notification-with-actions/page-notification-with-actions.component.ts
import { Component } from "@angular/core"
import { VegaNotify } from "@heartlandone/vega"

@Component({
  selector: "app-page-notification-with-actions",
  templateUrl: "./page-notification-with-actions.component.html",
  styleUrls: ["./page-notification-with-actions.component.scss"]
})
export class PageNotificationWithActionsComponent {
  async openNotifyWithAction(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    const id = await VegaNotify.open({
      title: "Title",
      duration: 0,
      message: "This notification will not be closed, because the duration is set 0",
      actionButtons: [
        {
          label: "Confirm",
          onVegaClick: () => {
            VegaNotify.close(id)
          }
        }
      ]
    })
  }

  async openNotifyWithActions(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    const id = await VegaNotify.open({
      title: "Title",
      duration: 10000,
      message: `This notification will close after 10s`,
      actionButtons: [
        {
          label: "Cancel",
          onVegaClick: () => {
            VegaNotify.close(id)
          }
        },
        {
          label: "OK",
          onVegaClick: () => {
            VegaNotify.close(id)
          }
        }
      ]
    })
  }
}

<vega-flex gap="size-16">
  <vega-button (vegaClick)="openNotifyWithAction($event)">With action</vega-button>
  <vega-button
    variant="secondary"
    (vegaClick)="openNotifyWithActions($event)"
  >
    With actions
  </vega-button>
</vega-flex>
