// vue-demo/src/components/carousel/examples/carousel.vue
<script>
import { VegaCarousel, VegaCard } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaCarousel, VegaCard }
}
</script>
<template>
  <VegaCarousel per-page="1" spacing="size-32" show-slider="true">
    <div>
      <VegaCard shadow="shadow-card" background-color="bg-primary" padding="size-24">
        <div class="v-text-primary v-font-p2-short">First page</div>
      </VegaCard>
    </div>
    <div>
      <VegaCard shadow="shadow-card" background-color="bg-primary" padding="size-24">
        <div class="v-text-primary v-font-p2-short">Second page</div>
      </VegaCard>
    </div>
    <div>
      <VegaCard shadow="shadow-card" background-color="bg-primary" padding="size-24">
        <div class="v-text-primary v-font-p2-short">Third page</div>
      </VegaCard>
    </div>
  </VegaCarousel>
</template>

// react-demo/src/components/carousel/examples/carousel.jsx
import { VegaCarousel, VegaCard } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaCarousel perPage={1} spacing={`size-32`} showSlider={true}>
      <div>
        <VegaCard
          shadow={`shadow-card`}
          backgroundColor={`bg-primary`}
          padding={`size-24`}
        >
          <div className={`v-text-primary v-font-p2-short`}>First page</div>
        </VegaCard>
      </div>
      <div>
        <VegaCard
          shadow={`shadow-card`}
          backgroundColor={`bg-primary`}
          padding={`size-24`}
        >
          <div className={`v-text-primary v-font-p2-short`}>Second page</div>
        </VegaCard>
      </div>
      <div>
        <VegaCard
          shadow={`shadow-card`}
          backgroundColor={`bg-primary`}
          padding={`size-24`}
        >
          <div className={`v-text-primary v-font-p2-short`}>Third page</div>
        </VegaCard>
      </div>
    </VegaCarousel>
  );
};
export default App;
