// vue-demo/src/components/textarea/examples/textarea.vue
<script>
import { VegaTextarea } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaTextarea }
}
</script>
<template>
  <VegaTextarea
    label="Description"
    value="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    :min-length="1"
    :max-length="100"
    :auto-validation="true"
    placeholder=""
    :disabled="false"
    hint="The maximum number of characters is 100"
    :show-counter="true"
  />
</template>

// react-demo/src/components/textarea/examples/textarea.jsx
import { VegaTextarea } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaTextarea
      label={`Description`}
      value={`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`}
      minLength={1}
      maxLength={100}
      autoValidation={true}
      placeholder={``}
      disabled={false}
      hint={`The maximum number of characters is 100`}
      showCounter={true}
    />
  );
};

export default App;
