// angular-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate/loading-indicator-circle-determinate.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-loading-indicator-circle-determinate",
  templateUrl: "./loading-indicator-circle-determinate.component.html",
  styleUrls: ["./loading-indicator-circle-determinate.component.scss"]
})
export class LoadingIndicatorCircleDeterminateComponent {}

<vega-loading-indicator
  mode="determinate"
  label="Loading Data 35%"
  hint="Please wait"
  [percent]="35"
  size="large"
/>

// vue-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate.vue
<script>
import { VegaLoadingIndicator } from "@heartlandone/vega-vue"
export default {
  data() {
    return {}
  },
  components: { VegaLoadingIndicator }
}
</script>
<template>
  <VegaLoadingIndicator
    mode="determinate"
    label="Loading Data 35%"
    hint="Please wait"
    :percent="35"
    size="large"
  />
</template>
