// angular-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate-error/loading-indicator-circle-determinate-error.component.ts
import { Component, OnInit, ViewChild, AfterViewInit } from "@angular/core"

@Component({
  selector: "app-loading-indicator-circle-determinate-error",
  templateUrl: "./loading-indicator-circle-determinate-error.component.html",
  styleUrls: ["./loading-indicator-circle-determinate-error.component.scss"]
})
export class LoadingIndicatorCircleDeterminateErrorComponent implements OnInit, AfterViewInit {
  constructor() {}
  percentage = 0
  @ViewChild("errorLoader") errorLoader!: HTMLVegaLoadingIndicatorElement

  simulatePercentage() {
    const errorLoaderElement = this.errorLoader
    errorLoaderElement.percent = 0
    this.percentage = 0
    const successLoaderTimer = setInterval(() => {
      if (errorLoaderElement.percent < 80) {
        errorLoaderElement.percent += 1
        errorLoaderElement.label = `${errorLoaderElement.percent}%`
      } else {
        errorLoaderElement.status = "error"
        errorLoaderElement.label = "Error"
        clearInterval(successLoaderTimer)
      }
    }, 30)
  }
  ngOnInit() {}
  ngAfterViewInit() {
    setTimeout(() => {
      this.simulatePercentage()
    }, 1000)
  }
}

<vega-flex direction="col">
  <vega-loading-indicator
    ngModel
    #errorLoader
    ngDefaultControl
    mode="determinate"
    [percent]="percentage"
    size="large"
  />
  <vega-flex gap="size-12">
    <vega-icon
      icon="far fa-rotate-right"
      (click)="simulatePercentage()"
    />
    <span
      (click)="simulatePercentage()"
      class="v-text-primary"
      >Refresh</span
    >
  </vega-flex>
</vega-flex>

// vue-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate-error.vue
<script>
import { VegaLoadingIndicator, VegaFlex, VegaIcon } from "@heartlandone/vega-vue"

export default {
  data() {
    return {
      percentage: 0
    }
  },
  components: { VegaLoadingIndicator, VegaFlex, VegaIcon },
  methods: {
    simulatePercentage() {
      const errorLoaderElement = this.$refs.errorLoader.$el
      errorLoaderElement.percent = 0
      this.percentage = 0
      const errorLoaderTimer = setInterval(() => {
        if (errorLoaderElement.percent < 80) {
          errorLoaderElement.percent += 1
          errorLoaderElement.label = `${errorLoaderElement.percent}%`
          errorLoaderElement.hint = null
        } else {
          errorLoaderElement.status = `error`
          errorLoaderElement.label = `Error`
          errorLoaderElement.hint = `${errorLoaderElement.percent}%`
          clearInterval(errorLoaderTimer)
        }
      }, 30)
    }
  },
  mounted() {
    this.simulatePercentage()
  }
}
</script>
<template>
  <VegaFlex direction="col">
    <VegaLoadingIndicator
      ref="errorLoader"
      mode="determinate"
      :percent="percentage"
      size="large"
    />
    <VegaFlex gap="size-12">
      <VegaIcon
        icon="far fa-rotate-right"
        @click="simulatePercentage"
      />
      <span
        @click="simulatePercentage"
        class="v-text-primary"
        >Refresh</span
      >
    </VegaFlex>
  </VegaFlex>
</template>
