// react-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate-success.jsx
import { useRef, useState, useEffect } from "react";
import {
  VegaLoadingIndicator,
  VegaFlex,
  VegaIcon,
} from "@heartlandone/vega-react";

const App = () => {
  const successLoader = useRef();
  let [percentage, setPercentage] = useState(0);
  const simulatePercentage = () => {
    successLoader.current.percent = 0;
    setPercentage(0);
    const successLoaderTimer = setInterval(() => {
      if (successLoader.current.percent < 100) {
        successLoader.current.percent += 1;
        successLoader.current.label = `${successLoader.current.percent}%`;
      } else {
        successLoader.current.status = "success";
        successLoader.current.Label = "Success";
        clearInterval(successLoaderTimer);
      }
    }, 30);
  };
  useEffect(() => {
    simulatePercentage();
  }, []);

  return (
    <VegaFlex direction={`col`}>
      <VegaLoadingIndicator
        ref={successLoader}
        mode={`determinate`}
        percent={percentage}
        size={`large`}
        label={`${percentage}%`}
      />
      <VegaIcon icon={`far fa-rotate-right`} onClick={simulatePercentage} />
    </VegaFlex>
  );
};
export default App;

// vue-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate-success.vue
<script>
import { VegaLoadingIndicator, VegaFlex, VegaIcon } from "@heartlandone/vega-vue"

export default {
  data() {
    return {
      percentage: 0
    }
  },
  components: { VegaLoadingIndicator, VegaFlex, VegaIcon },
  methods: {
    simulatePercentage() {
      const successLoaderElement = this.$refs.successLoader.$el
      successLoaderElement.percent = 0
      this.percentage = 0
      const successLoaderTimer = setInterval(() => {
        if (successLoaderElement.percent < 100) {
          successLoaderElement.percent += 1
          successLoaderElement.label = `${successLoaderElement.percent}%`
        } else {
          successLoaderElement.status = "success"
          successLoaderElement.Label = "Success"
          clearInterval(successLoaderTimer)
        }
      }, 30)
    }
  },
  mounted() {
    this.simulatePercentage()
  }
}
</script>
<template>
  <VegaFlex direction="col">
    <VegaLoadingIndicator
      ref="successLoader"
      mode="determinate"
      :percent="percentage"
      size="large"
      :label="percentage + '%'"
    />
    <VegaFlex gap="size-12">
      <VegaIcon
        icon="far fa-rotate-right"
        @click="simulatePercentage"
      />
      <span
        @click="simulatePercentage"
        class="v-text-primary"
        >Refresh</span
      >
    </VegaFlex>
  </VegaFlex>
</template>
