// react-demo/src/components/loading-indicator/examples/loading-indicator-bar-determinate.jsx
import { VegaLoadingIndicator } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaLoadingIndicator
      mode={`determinate`}
      shape={`bar`}
      label={`Loading Data 35%`}
      hint={`Please wait`}
      percent={35}
      size={`large`}
    />
  );
};
export default App;

// vue-demo/src/components/loading-indicator/examples/loading-indicator-bar-determinate.vue
<script>
import { VegaLoadingIndicator } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaLoadingIndicator }
}
</script>
<template>
  <VegaLoadingIndicator
    mode="determinate"
    shape="bar"
    label="Loading Data 35%"
    hint="Please wait"
    :percent="35"
    size="large"
  />
</template>
