// react-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate-error.jsx
import { useRef, useState, useEffect } from "react";
import {
  VegaLoadingIndicator,
  VegaFlex,
  VegaIcon,
} from "@heartlandone/vega-react";

const App = () => {
  const errorLoader = useRef();
  let [percentage, setPercentage] = useState(0);
  const simulatePercentage = () => {
    errorLoader.current.percent = 0;
    setPercentage(0);
    const errorLoaderTimer = setInterval(() => {
      if (errorLoader.current.percent < 80) {
        errorLoader.current.percent += 1;
        errorLoader.current.label = `${errorLoader.current.percent}%`;
        errorLoader.current.hint = null;
      } else {
        errorLoader.current.status = `error`;
        errorLoader.current.label = `Error`;
        errorLoader.current.hint = `${errorLoader.current.percent}%`;
        clearInterval(errorLoaderTimer);
      }
    }, 30);
  };
  useEffect(() => {
    simulatePercentage();
  }, []);

  return (
    <VegaFlex direction={`col`}>
      <VegaLoadingIndicator
        ref={errorLoader}
        mode={`determinate`}
        percent={percentage}
        size={`large`}
      />
      <VegaIcon icon={`far fa-rotate-right`} onClick={simulatePercentage} />
    </VegaFlex>
  );
};
export default App;

// vue-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate-error.vue
<script>
import { VegaLoadingIndicator, VegaFlex, VegaIcon } from "@heartlandone/vega-vue"

export default {
  data() {
    return {
      percentage: 0
    }
  },
  components: { VegaLoadingIndicator, VegaFlex, VegaIcon },
  methods: {
    simulatePercentage() {
      const errorLoaderElement = this.$refs.errorLoader.$el
      errorLoaderElement.percent = 0
      this.percentage = 0
      const errorLoaderTimer = setInterval(() => {
        if (errorLoaderElement.percent < 80) {
          errorLoaderElement.percent += 1
          errorLoaderElement.label = `${errorLoaderElement.percent}%`
          errorLoaderElement.hint = null
        } else {
          errorLoaderElement.status = `error`
          errorLoaderElement.label = `Error`
          errorLoaderElement.hint = `${errorLoaderElement.percent}%`
          clearInterval(errorLoaderTimer)
        }
      }, 30)
    }
  },
  mounted() {
    this.simulatePercentage()
  }
}
</script>
<template>
  <VegaFlex direction="col">
    <VegaLoadingIndicator
      ref="errorLoader"
      mode="determinate"
      :percent="percentage"
      size="large"
    />
    <VegaFlex gap="size-12">
      <VegaIcon
        icon="far fa-rotate-right"
        @click="simulatePercentage"
      />
      <span
        @click="simulatePercentage"
        class="v-text-primary"
        >Refresh</span
      >
    </VegaFlex>
  </VegaFlex>
</template>
