// angular-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate-success/loading-indicator-circle-determinate-success.component.ts
import { Component, OnInit, ViewChild, AfterViewInit } from "@angular/core"

@Component({
  selector: "app-loading-indicator-circle-determinate-success",
  templateUrl: "./loading-indicator-circle-determinate-success.component.html",
  styleUrls: ["./loading-indicator-circle-determinate-success.component.scss"]
})
export class LoadingIndicatorCircleDeterminateSuccessComponent implements OnInit, AfterViewInit {
  constructor() {}
  percentage = 0
  @ViewChild("successLoader") successLoader!: HTMLVegaLoadingIndicatorElement

  simulatePercentage() {
    const successLoaderElement = this.successLoader
    successLoaderElement.percent = 0
    this.percentage = 0
    const successLoaderTimer = setInterval(() => {
      if (successLoaderElement.percent < 100) {
        successLoaderElement.percent += 1
        successLoaderElement.label = `${successLoaderElement.percent}%`
      } else {
        successLoaderElement.status = "success"
        successLoaderElement.label = "Success"
        clearInterval(successLoaderTimer)
      }
    }, 30)
  }
  ngOnInit() {}
  ngAfterViewInit() {
    setTimeout(() => {
      this.simulatePercentage()
    }, 1000)
  }
}

<vega-flex direction="col">
  <vega-loading-indicator
    ngModel
    #successLoader
    ngDefaultControl
    mode="determinate"
    [percent]="percentage"
    size="large"
    [label]="percentage + '%'"
  />
  <vega-flex gap="size-12">
    <vega-icon
      icon="far fa-rotate-right"
      (click)="simulatePercentage()"
    />
    <span
      (click)="simulatePercentage()"
      class="v-text-primary"
      >Refresh</span
    >
  </vega-flex>
</vega-flex>

// vue-demo/src/components/loading-indicator/examples/loading-indicator-circle-determinate-success.vue
<script>
import { VegaLoadingIndicator, VegaFlex, VegaIcon } from "@heartlandone/vega-vue"

export default {
  data() {
    return {
      percentage: 0
    }
  },
  components: { VegaLoadingIndicator, VegaFlex, VegaIcon },
  methods: {
    simulatePercentage() {
      const successLoaderElement = this.$refs.successLoader.$el
      successLoaderElement.percent = 0
      this.percentage = 0
      const successLoaderTimer = setInterval(() => {
        if (successLoaderElement.percent < 100) {
          successLoaderElement.percent += 1
          successLoaderElement.label = `${successLoaderElement.percent}%`
        } else {
          successLoaderElement.status = "success"
          successLoaderElement.Label = "Success"
          clearInterval(successLoaderTimer)
        }
      }, 30)
    }
  },
  mounted() {
    this.simulatePercentage()
  }
}
</script>
<template>
  <VegaFlex direction="col">
    <VegaLoadingIndicator
      ref="successLoader"
      mode="determinate"
      :percent="percentage"
      size="large"
      :label="percentage + '%'"
    />
    <VegaFlex gap="size-12">
      <VegaIcon
        icon="far fa-rotate-right"
        @click="simulatePercentage"
      />
      <span
        @click="simulatePercentage"
        class="v-text-primary"
        >Refresh</span
      >
    </VegaFlex>
  </VegaFlex>
</template>
