// vue-demo/src/components/carousel/examples/carousel.vue
<script>
import { VegaCarousel, VegaCard } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaCarousel, VegaCard }
}
</script>
<template>
  <VegaCarousel per-page="1" spacing="size-32" show-slider="true">
    <div>
      <VegaCard shadow="shadow-card" background-color="bg-primary" padding="size-24">
        <div class="v-text-primary v-font-p2-short">First page</div>
      </VegaCard>
    </div>
    <div>
      <VegaCard shadow="shadow-card" background-color="bg-primary" padding="size-24">
        <div class="v-text-primary v-font-p2-short">Second page</div>
      </VegaCard>
    </div>
    <div>
      <VegaCard shadow="shadow-card" background-color="bg-primary" padding="size-24">
        <div class="v-text-primary v-font-p2-short">Third page</div>
      </VegaCard>
    </div>
  </VegaCarousel>
</template>

// angular-demo/src/components/carousel/examples/carousel/carousel.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-carousel",
  templateUrl: "./carousel.component.html",
  styleUrls: ["./carousel.component.scss"]
})
export class CarouselComponent {}

<vega-carousel
  per-page="1"
  spacing="size-32"
  show-slider="true"
>
  <div>
    <vega-card
      shadow="shadow-card"
      background-color="bg-primary"
      padding="size-24"
    >
      <div class="v-text-primary v-font-p2-short">First page</div>
    </vega-card>
  </div>
  <div>
    <vega-card
      shadow="shadow-card"
      background-color="bg-primary"
      padding="size-24"
    >
      <div class="v-text-primary v-font-p2-short">Second page</div>
    </vega-card>
  </div>
  <div>
    <vega-card
      shadow="shadow-card"
      background-color="bg-primary"
      padding="size-24"
    >
      <div class="v-text-primary v-font-p2-short">Third page</div>
    </vega-card>
  </div>
</vega-carousel>
