// vue-demo/src/components/table/examples/table-editable.vue
<script>
import { VegaTable, VegaFlex, VegaCard, VegaButtonLink, VegaButton } from "@heartlandone/vega-vue"

export default {
  data() {
    return {
      dataSource: [
        {
          key: "1",
          employeeId: "1",
          name: "Employee 1",
          balance: 100
        },
        {
          key: "2",
          employeeId: "2",
          name: "Employee 2",
          balance: 300
        }
      ],
      editedData: null
    }
  },
  components: { VegaTable, VegaFlex, VegaCard, VegaButtonLink, VegaButton },
  methods: {
    confirmDialog(string, callback) {
      if (window.confirm(string)) {
        callback()
      }
    },
    printDataResult(data) {
      this.editedData = data
    },
    async onAddNew() {
      await this.$refs.tableRef.$el.addNewRow()
    },

    saveRow(index, record) {
      this.dataSource[index] = record
    },

    async onSaveRowData() {
      const rowData = await this.$refs.tableRef.$el.getRowsData()
      this.dataSource = rowData
      this.printDataResult(rowData)
    }
  }
}
</script>
<template>
  <VegaFlex direction="col">
    <VegaCard>
      <VegaTable
        ref="tableRef"
        :row-clickable="true"
        :columns="[
          {
            label: 'ID #',
            prop: 'employeeId',
            editable: true
          },
          {
            label: 'Name',
            prop: 'name',
            editable: true
          },
          {
            label: 'Balance',
            prop: 'balance',
            editable: true
          },
          {
            label: 'Actions',
            width: '120px',
            renderFormItem: (createElement, rowKey, record, index, { rowForm, isNewRow }) => {
              return createElement('div', {}, [
                createElement('vega-button-circle', {
                  variant: 'icon-only',
                  icon: 'checkmark',
                  onVegaClick: async () => {
                    this.$refs.tableRef.$el.saveEditRow(rowKey)
                    const data = await this.$refs.tableRef.$el.getRowData(rowKey)
                    saveRow(index, data)
                    printDataResult(data)
                  }
                }),
                createElement('vega-button-circle', {
                  variant: 'icon-only',
                  icon: 'close',
                  class: !isNewRow ? '' : 'v-hidden',
                  onVegaClick: () => {
                    this.$refs.tableRef.$el.stopRowEditMode(rowKey)
                  }
                }),
                createElement('vega-button-circle', {
                  variant: 'icon-only',
                  icon: 'delete-bin',
                  class: isNewRow ? '' : 'v-hidden',
                  danger: true,
                  onVegaClick: () => {
                    this.confirmDialog('Are you sure you want to delete this row?', () => {
                      this.$refs.tableRef.$el.removeRow(record.key)
                    })
                  }
                })
              ])
            },
            render: (h, rowKey) => {
              return h('div', {}, [
                h('vega-button-circle', {
                  variant: 'icon-only',
                  icon: 'edit-line',
                  onVegaClick: () => {
                    this.$refs.tableRef.$el.startRowEditMode(rowKey)
                  }
                }),
                h('vega-button-circle', {
                  variant: 'icon-only',
                  icon: 'delete-bin',
                  danger: true,
                  onVegaClick: async () => {
                    this.confirmDialog('Are you sure you want to delete this row?', async () => {
                      await this.$refs.tableRef.$el.removeRow(rowKey)
                    })
                  }
                })
              ])
            }
          }
        ]"
        :data-source="dataSource"
      />
      <div class="v-mt-size-12 v-font-p2-short v-text-primary">
        <VegaButtonLink
          size="small"
          icon="plus-sign"
          @vegaclick="onAddNew"
        >
          Add New
        </VegaButtonLink>
      </div>
    </VegaCard>
    <div class="v-mt-size-12">
      <vega-flex gap="size-8">
        <VegaButton
          size="small"
          @vegaclick="onSaveRowData"
        >
          Get All Rows Data & Save
        </VegaButton>
      </vega-flex>
    </div>
    <div class="v-mt-size-8 v-text-primary">
      <div class="v-font-field-label v-text-success">Saved Data:</div>
      <div class="v-font-field-label">
        {{ JSON.stringify(editedData, null, 2) }}
      </div>
    </div>
  </VegaFlex>
</template>

// angular-demo/src/components/table/examples/table-editable/table-editable.component.ts
import { Component, ViewChild } from "@angular/core"
import {
  VegaTableCellFormItemRenderFunction,
  VegaTableCellRenderFunction,
  VegaTableCreateElementFunction,
  VegaTableDataSourceItem
} from "@heartlandone/vega"

export interface tableColumnsType {
  label: string
  prop?: string
  editable?: boolean
  width?: string
  renderFormItem?: VegaTableCellFormItemRenderFunction
  render?: VegaTableCellRenderFunction
}
export interface dataSourceType {
  key: string
  employeeId: string
  balance: number
  name: string
}
@Component({
  selector: "app-table-editable",
  templateUrl: "./table-editable.component.html",
  styleUrls: ["./table-editable.component.scss"]
})
export class TableEditableComponent {
  @ViewChild("table") table!: HTMLVegaTableElement
  editedData = null
  columns: tableColumnsType[] = [
    {
      label: "ID #",
      prop: "employeeId",
      editable: true
    },
    {
      label: "Name",
      prop: "name",
      editable: true
    },
    {
      label: "Balance",
      prop: "balance",
      editable: true
    },
    {
      label: "Actions",
      width: "120px",
      renderFormItem: (
        createElement: VegaTableCreateElementFunction,
        rowKey: any,
        record: VegaTableDataSourceItem,
        index: number,
        rowPayload: { rowForm: HTMLVegaFormElement; isNewRow: boolean }
      ) => {
        return createElement("div", {}, [
          createElement("vega-button-circle", {
            variant: "icon-only",
            icon: "checkmark",
            onVegaClick: async () => {
              this.table.saveEditRow(rowKey)
              const data = await this.table.getRowData(rowKey)
              this.saveRow(index, data)
              this.printDataResult(data)
            }
          }),
          createElement("vega-button-circle", {
            variant: "icon-only",
            icon: "close",
            class: !rowPayload.isNewRow ? "" : "v-hidden",
            onVegaClick: () => {
              this.table.stopRowEditMode(rowKey)
            }
          }),
          createElement("vega-button-circle", {
            variant: "icon-only",
            icon: "delete-bin",
            class: rowPayload.isNewRow ? "" : "v-hidden",
            danger: true,
            onVegaClick: () => {
              const recordKey: any = record.key
              this.confirmDialog("Are you sure you want to delete this row?", () => {
                this.table.removeRow(recordKey)
              })
            }
          })
        ])
      },
      render: (h: any, rowKey: any) => {
        return h("div", {}, [
          h("vega-button-circle", {
            variant: "icon-only",
            icon: "edit-line",
            onVegaClick: () => {
              this.table.startRowEditMode(rowKey)
            }
          }),
          h("vega-button-circle", {
            variant: "icon-only",
            icon: "delete-bin",
            danger: true,
            onVegaClick: async () => {
              this.confirmDialog("Are you sure you want to delete this row?", async () => {
                await this.table.removeRow(rowKey)
              })
            }
          })
        ])
      }
    }
  ]
  dataSource: dataSourceType[] = [
    {
      key: "1",
      employeeId: "1",
      name: "Employee 1",
      balance: 100
    },
    {
      key: "2",
      employeeId: "2",
      name: "Employee 2",
      balance: 300
    }
  ]

  confirmDialog(string: string, callback: any) {
    if (window.confirm(string)) {
      callback()
    }
  }
  printDataResult(data: any) {
    this.editedData = data
  }
  async onAddNew() {
    await this.table.addNewRow()
  }

  saveRow(index: number, record: any) {
    this.dataSource[index] = record
  }

  async onSaveRowData() {
    const rowData = await this.table.getRowsData()
    this.printDataResult(rowData)
  }
  stringifySavedData(data: any) {
    return JSON.stringify(data, null, 2)
  }
}

<vega-flex direction="col">
  <vega-card>
    <vega-table
      ngModel
      #table
      ngDefaultControl
      [rowClickable]="true"
      [columns]="columns"
      [dataSource]="dataSource"
    />
    <div class="v-mt-size-12 v-font-p2-short v-text-primary">
      <vega-button-link
        size="small"
        icon="plus-sign"
        (vegaClick)="onAddNew()"
      >
        Add New
      </vega-button-link>
    </div>
  </vega-card>
  <div class="v-mt-size-12">
    <vega-flex gap="size-8">
      <vega-button
        size="small"
        (vegaClick)="onSaveRowData()"
      >
        Get All Rows Data & Save
      </vega-button>
    </vega-flex>
  </div>
  <div class="v-mt-size-8 v-text-primary">
    <div class="v-font-field-label v-text-success">Saved Data:</div>
    <div class="v-font-field-label">
      {{ stringifySavedData(editedData) }}
    </div>
  </div>
</vega-flex>
