// react-demo/src/components/combo-box/examples/combo-box.jsx
import { VegaComboBox } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaComboBox
      label={`label text`}
      required={true}
      source={[
        { key: "key1", label: "option 1" },
        { key: "key2", label: "option 2" },
        { key: "key3", label: "option 3" },
      ]}
    />
  );
};
export default App;

// angular-demo/src/components/combo-box/examples/combo-box/combo-box.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-combo-box",
  templateUrl: "./combo-box.component.html",
  styleUrls: ["./combo-box.component.scss"]
})
export class ComboBoxComponent {}

<vega-combo-box
  label="label text"
  [required]="true"
  [source]="[
    { key: 'key1', label: 'option 1' },
    { key: 'key2', label: 'option 2' },
    { key: 'key3', label: 'option 3' }
  ]"
/>
