// vue-demo/src/components/image-uploader/examples/image-uploader.vue
<script>
import { VegaImageUploader } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaImageUploader },
  methods: {
    async onChange(evt) {
      if (evt.detail) {
        this.$refs.uploader.$el.status = "uploading"
        setTimeout(() => {
          this.$refs.uploader.$el.status = "done"
        }, 3000)
      }
    }
  }
}
</script>
<template>
  <VegaImageUploader
    ref="uploader"
    @vegachange="onChange"
  />
</template>

// react-demo/src/components/image-uploader/examples/image-uploader.jsx
import { useRef } from "react";
import { VegaImageUploader } from "@heartlandone/vega-react";

const App = () => {
  const uploader = useRef();
  const onChange = async (evt) => {
    if (evt.detail) {
      uploader.current.status = "uploading";
      setTimeout(() => {
        uploader.current.status = "done";
      }, 3000);
    }
  };
  return <VegaImageUploader ref={uploader} onVegaChange={onChange} />;
};
export default App;
