// angular-demo/src/components/counter-badge/examples/counter-badge/counter-badge.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-counter-badge",
  templateUrl: "./counter-badge.component.html",
  styleUrls: ["./counter-badge.component.scss"]
})
export class CounterBadgeComponent {}

<vega-counter-badge
  [offset]="[5, 0]"
  color="bg-danger"
  [dot]="false"
  [count]="9"
>
  <vega-button>Button Example</vega-button>
</vega-counter-badge>

// vue-demo/src/components/counter-badge/examples/counter-badge.vue
<script>
import { VegaCounterBadge, VegaButton } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaCounterBadge, VegaButton }
}
</script>
<template>
  <VegaCounterBadge :offset="[5, 0]" color="bg-danger" :dot="false" :count="9">
    <VegaButton>Button Example</VegaButton>
  </VegaCounterBadge>
</template>
