// angular-demo/src/components/counter-badge/examples/counter-badge-with-dot/counter-badge-with-dot.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-counter-badge-with-dot",
  templateUrl: "./counter-badge-with-dot.component.html",
  styleUrls: ["./counter-badge-with-dot.component.scss"]
})
export class CounterBadgeWithDotComponent {}

<vega-counter-badge
  color="bg-danger"
  [dot]="true"
  [count]="9"
>
  <vega-button>Button Example</vega-button>
</vega-counter-badge>

// vue-demo/src/components/counter-badge/examples/counter-badge-with-dot.vue
<script>
import { VegaCounterBadge, VegaButton } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaCounterBadge, VegaButton }
}
</script>
<template>
  <VegaCounterBadge color="bg-danger" :dot="true" :count="9">
    <VegaButton>Button Example</VegaButton>
  </VegaCounterBadge>
</template>
