// angular-demo/src/components/tab-group/examples/tab-group/tab-group.component.ts
import { Component } from "@angular/core"

export interface TabItems {
  label: string
  dataTarget: string
  prefixIcon?: string
}
@Component({
  selector: "app-tab-group",
  templateUrl: "./tab-group.component.html",
  styleUrls: ["./tab-group.component.scss"]
})
export class TabGroupComponent {
  tabItems: TabItems[] = [
    { label: "Home", dataTarget: "nav-home", prefixIcon: "home" },
    { label: "Profile", dataTarget: "nav-profile" },
    { label: "Contact", dataTarget: "nav-contact" }
  ]
  onTabClick(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    console.log(customEvent.detail)
  }
}

<vega-flex direction="col">
  <vega-tab-group
    gap="size-8"
    [showCloseButton]="false"
    [tabItems]="tabItems"
    (vegaClick)="onTabClick($event)"
  >
    <vega-tab-group-panel
      id="nav-home"
      class="v-py-size-24"
    >
      <div class="v-font-p2-short v-text-primary">This is the Home tab</div>
    </vega-tab-group-panel>

    <vega-tab-group-panel
      id="nav-profile"
      class="v-py-size-24"
    >
      <div class="v-font-p2-short v-text-primary">Profile tab</div>
    </vega-tab-group-panel>

    <vega-tab-group-panel
      id="nav-contact"
      class="v-py-size-24"
    >
      <div class="v-font-p2-short v-text-primary">Contact tab</div>
    </vega-tab-group-panel>
  </vega-tab-group>
</vega-flex>

// react-demo/src/components/tab-group/examples/tab-group.jsx
import {
  VegaTabGroup,
  VegaTabGroupPanel,
  VegaFlex,
} from "@heartlandone/vega-react";

const App = () => {
  const onTabClick = (e) => {
    console.log(e.detail);
  };
  return (
    <VegaFlex direction={`col`}>
      <VegaTabGroup
        gap={`size-8`}
        showCloseButton={false}
        tabItems={[
          { label: "Home", dataTarget: "nav-home", prefixIcon: "home" },
          { label: "Profile", dataTarget: "nav-profile" },
          { label: "Contact", dataTarget: "nav-contact" },
        ]}
        onVegaClick={onTabClick}
      >
        <VegaTabGroupPanel id={`nav-home`} className={`v-py-size-24`}>
          <div className={`v-font-p2-short v-text-primary`}>
            This is the Home tab
          </div>
        </VegaTabGroupPanel>

        <VegaTabGroupPanel id={`nav-profile`} className={`v-py-size-24`}>
          <div className={`v-font-p2-short v-text-primary`}>Profile tab</div>
        </VegaTabGroupPanel>

        <VegaTabGroupPanel id={`nav-contact`} className={`v-py-size-24`}>
          <div className={`v-font-p2-short v-text-primary`}>Contact tab</div>
        </VegaTabGroupPanel>
      </VegaTabGroup>
    </VegaFlex>
  );
};
export default App;
