// angular-demo/src/app/component-sub-content/component-sub-content.component.ts
import { Component, Input } from "@angular/core"

@Component({
  selector: "app-component-sub-content",
  templateUrl: "./component-sub-content.component.html",
  styleUrls: ["./component-sub-content.component.scss"]
})
export class ComponentSubContentComponent {
  @Input() subTitle!: string
  @Input() background!: boolean
}

<div>
  <ng-content></ng-content>
</div>

<div class="v-mb-size-24">
  <div class="v-font-btn-label v-text-primary v-mb-size-12">
    {{ subTitle }}
  </div>
  <div class="v-mb-size-32">
    <div class="v-bg-backdrop-popover v-p-size-24 v-rounded-12">
      <div class="v-bg-primary v-p-size-24 v-rounded-12">
        <ng-content></ng-content>
      </div>
    </div>
  </div>
</div>

// react-demo/src/routes/components/ComponentSubContent.jsx
export default function ComponentSubContent(props) {
  return (
    <div className={`v-mb-size-24`}>
      <div className={`v-font-btn-label v-text-primary v-mb-size-12`}>
        {props.subTitle}
      </div>
      <div className={`v-mb-size-32`}>
        <div
          className={
            props.background
              ? `v-bg-backdrop-popover v-p-size-24 v-rounded-12`
              : `v-px-size-12`
          }
        >
          {props.background === true ? (
            <div className={`v-bg-primary v-p-size-24 v-rounded-12`}>
              {props.children}
            </div>
          ) : (
            <div>{props.children}</div>
          )}
        </div>
      </div>
    </div>
  );
}
