// react-demo/src/components/combo-box/examples/combo-box-with-creatable-options.jsx
import { useRef } from "react";
import { VegaComboBox } from "@heartlandone/vega-react";

const App = () => {
  const comboBox = useRef();
  const onCreate = (evt) => {
    comboBox.current.source.push({ key: evt.detail, label: evt.detail });
    comboBox.current.value = [...comboBox.current.value, evt.detail];
  };
  return (
    <VegaComboBox
      ref={comboBox}
      label={`label text`}
      required={true}
      source={[
        { key: "key1", label: "option 1" },
        { key: "key2", label: "option 2" },
        { key: "key3", label: "option 3" },
      ]}
      vegaDropdownProps={{ dynamicOption: true }}
      onVegaCreate={onCreate}
    />
  );
};
export default App;

// angular-demo/src/components/combo-box/examples/combo-box-with-creatable-options/combo-box-with-creatable-options.component.ts
import { Component, ViewChild } from "@angular/core"

@Component({
  selector: "app-combo-box-with-creatable-options",
  templateUrl: "./combo-box-with-creatable-options.component.html",
  styleUrls: ["./combo-box-with-creatable-options.component.scss"]
})
export class ComboBoxWithCreatableOptionsComponent {
  onCreate(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent<any>
    const comboBox: HTMLVegaComboBoxElement = e.target as HTMLVegaComboBoxElement
    const value = customEvent.detail

    comboBox.source.push({ key: value, label: value })
    comboBox.value = [...comboBox.value, value]
  }
}

<vega-combo-box
  label="label text"
  [required]="true"
  [source]="[
    { key: 'key1', label: 'option 1' },
    { key: 'key2', label: 'option 2' },
    { key: 'key3', label: 'option 3' }
  ]"
  [vegaDropdownProps]="{ dynamicOption: true }"
  (vegaCreate)="onCreate($event)"
/>
