// vue-demo/src/components/button-circle/examples/button-circle-danger.vue
<script>
import { VegaButtonCircle } from "@heartlandone/vega-vue"
export default {
  data() {
    return {}
  },
  components: { VegaButtonCircle },
  methods: {
    onClick() {}
  }
}
</script>

<template>
  <VegaButtonCircle
    variant="primary"
    size="small"
    icon="close"
    label="This is a danger button"
    danger="true"
    @vegaclick="onClick"
  />
</template>

// react-demo/src/components/button-circle/examples/button-circle-danger.jsx
import { VegaButtonCircle } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaButtonCircle
      variant={`primary`}
      disabled={false}
      size={`small`}
      icon={`close`}
      label={`This labels the button`}
      danger={true}
    />
  );
};

export default App;
