// angular-demo/src/components/button-circle/examples/button-circle-danger/button-circle-danger.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-button-circle-danger",
  templateUrl: "./button-circle-danger.component.html",
  styleUrls: ["./button-circle-danger.component.scss"]
})
export class ButtonCircleDangerComponent {
  onClick(e: Event) {}
}

<vega-button-circle
  variant="primary"
  size="small"
  icon="close"
  label="This is a danger button"
  danger="true"
  (vegaClick)="onClick($event)"
/>

// react-demo/src/components/button-circle/examples/button-circle-danger.jsx
import { VegaButtonCircle } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaButtonCircle
      variant={`primary`}
      disabled={false}
      size={`small`}
      icon={`close`}
      label={`This labels the button`}
      danger={true}
    />
  );
};

export default App;
