// react-demo/src/components/color-picker/examples/color-picker-with-color-array.jsx
import { useState } from "react";
import { VegaColorPicker, VegaFlex } from "@heartlandone/vega-react";

const App = () => {
  const [color, setColor] = useState("#CCCCCC");
  const onColorPickerChange = (evt) => {
    setColor(evt.currentTarget.value);
  };
  return (
    <VegaFlex direction={`col`}>
      <VegaColorPicker
        label={`Choose a Color`}
        value={color}
        autoValidation={true}
        hint={`Select a color from the list`}
        colors={[
          "#FFFFFF",
          "#000000",
          "#FF0000",
          "#CCCCCC",
          "#0000FF",
          "#00FFCC",
          "#FF00FF",
          "#99CC00",
        ]}
        onVegaChange={onColorPickerChange}
      />
      <div
        style={{
          marginTop: "12px",
          borderRadius: "8px",
          width: "200px",
          height: "200px",
          backgroundColor: color,
        }}
      />
    </VegaFlex>
  );
};

export default App;

// angular-demo/src/components/color-picker/examples/color-picker-with-color-array/color-picker-with-color-array.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-color-picker-with-color-array",
  templateUrl: "./color-picker-with-color-array.component.html",
  styleUrls: ["./color-picker-with-color-array.component.scss"]
})
export class ColorPickerWithColorArrayComponent {
  color = "#73E6DC"
  onColorPickerChange(e: Event) {
    const colorPicker: HTMLVegaColorPickerElement = e.target as HTMLVegaColorPickerElement
    this.color = colorPicker.value
  }
}

<vega-flex direction="col">
  <vega-color-picker
    label="Choose a Color"
    [value]="color"
    [autoValidation]="true"
    hint="Select a color from the list"
    (vegaChange)="onColorPickerChange($event)"
    [colors]="[
      '#FFFFFF',
      '#000000',
      '#FF0000',
      '#73E6DC',
      '#0000FF',
      '#00FFCC',
      '#FF00FF',
      '#99CC00'
    ]"
  />
  <div
    [style]="{
      marginTop: '12px',
      borderRadius: '8px',
      width: '200px',
      height: '200px',
      backgroundColor: color
    }"
  ></div>
</vega-flex>
