// vue-demo/src/components/date-picker/examples/date-picker.vue
<script>
import { VegaDatePicker } from '@heartlandone/vega-vue'
export default {
  data() {
    return {}
  },
  components: { VegaDatePicker }
}
</script>
<template>
  <VegaDatePicker
    label="Single mode"
    mode="single"
    size="small"
    format="MM/DD/YYYY"
    :clear-button="true"
  />
</template>

// angular-demo/src/components/date-picker/examples/date-picker/date-picker.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-date-picker",
  templateUrl: "./date-picker.component.html",
  styleUrls: ["./date-picker.component.scss"]
})
export class DatePickerComponent {}

<vega-date-picker
  label="Single mode"
  mode="single"
  size="small"
  format="MM/DD/YYYY"
  [clearButton]="true"
/>
