// angular-demo/src/components/loading-indicator/examples/loading-indicator-bar-determinate/loading-indicator-bar-determinate.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-loading-indicator-bar-determinate",
  templateUrl: "./loading-indicator-bar-determinate.component.html",
  styleUrls: ["./loading-indicator-bar-determinate.component.scss"]
})
export class LoadingIndicatorBarDeterminateComponent {}

<vega-loading-indicator
  mode="determinate"
  shape="bar"
  label="Loading Data 35%"
  hint="Please wait"
  [percent]="35"
  size="large"
/>

// react-demo/src/components/loading-indicator/examples/loading-indicator-bar-determinate.jsx
import { VegaLoadingIndicator } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaLoadingIndicator
      mode={`determinate`}
      shape={`bar`}
      label={`Loading Data 35%`}
      hint={`Please wait`}
      percent={35}
      size={`large`}
    />
  );
};
export default App;
