// angular-demo/src/components/input-select/examples/input-select/input-select.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-input-select",
  templateUrl: "./input-select.component.html",
  styleUrls: ["./input-select.component.scss"]
})
export class InputSelectComponent {}

<vega-input-select
  [required]="false"
  placeholder="placeholder text"
  max-height="400"
  [autoValidation]="true"
  [source]="[
    { id: 'id1', displayName: 'name1' },
    { id: 'id2', displayName: 'name2' },
    { id: 'id3', displayName: 'name3' },
    { id: 'id4', displayName: 'name4' }
  ]"
/>

// react-demo/src/components/input-select/examples/input-select.jsx
import { VegaInputSelect } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaInputSelect
      required={false}
      placeholder={`placeholder text`}
      maxHeight={400}
      autoValidation={true}
      source={[
        { id: "id1", displayName: "name1" },
        { id: "id2", displayName: "name2" },
        { id: "id3", displayName: "name3" },
        { id: "id4", displayName: "name4" },
      ]}
    />
  );
};
export default App;
