// react-demo/src/components/pagination/examples/pagination-with-number-of-pages-viewed.jsx
import { useRef, useEffect } from "react";
import { VegaPagination } from "@heartlandone/vega-react";

const App = () => {
  const recordsPagination = useRef();
  useEffect(() => {
    recordsPagination.current.extensions = [
      ["currentPageLabel"],
      ["pageSelector"],
    ];
  });
  return (
    <VegaPagination
      ref={recordsPagination}
      current={1}
      pageSize={10}
      total={100}
    />
  );
};
export default App;

// angular-demo/src/components/pagination/examples/pagination-with-number-of-pages-viewed/pagination-with-number-of-pages-viewed.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-pagination-with-number-of-pages-viewed",
  templateUrl: "./pagination-with-number-of-pages-viewed.component.html",
  styleUrls: ["./pagination-with-number-of-pages-viewed.component.scss"]
})
export class PaginationWithNumberOfPagesViewedComponent {}

<vega-pagination
  [current]="1"
  [pageSize]="10"
  [total]="100"
  [extensions]="[['currentPageLabel'], ['pageSelector']]"
/>
