// react-demo/src/components/chip/examples/chip.jsx
import { useRef } from "react";
import { VegaChip } from "@heartlandone/vega-react";

const App = () => {
  const chip = useRef();
  const closeChip = () => {
    chip.current.remove();
  };
  return (
    <VegaChip
      ref={chip}
      text={`Chip`}
      clickable={true}
      showCloseIcon={true}
      onVegaClick={null}
      onVegaClose={closeChip}
    />
  );
};
export default App;

// angular-demo/src/components/chip/examples/chip/chip.component.ts
import { Component, ViewChild } from "@angular/core"

@Component({
  selector: "app-chip",
  templateUrl: "./chip.component.html",
  styleUrls: ["./chip.component.scss"]
})
export class ChipComponent {
  @ViewChild("chip") chip!: HTMLVegaChipElement
  closeChip() {
    console.log(this.chip)
    this.chip.remove()
  }
}

<vega-chip
  ngModel
  #chip
  text="Chip"
  [clickable]="true"
  [showCloseIcon]="true"
  (vegaClick)="(null)"
  (vegaClose)="closeChip()"
/>
