// vue-demo/src/components/checkbox/examples/checkbox-group.vue
<script>
import { VegaCheckbox, VegaCheckboxGroup } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaCheckbox, VegaCheckboxGroup }
}
</script>
<template>
  <VegaCheckboxGroup
    :vega-flex-prop="{ gap: 'size-12', direction: 'col' }"
    :value="['apple', 'banana']"
  >
    <VegaCheckbox
      identifier="apple"
      size="small"
    >
      Apple
    </VegaCheckbox>
    <VegaCheckbox
      identifier="banana"
      size="small"
    >
      Banana
    </VegaCheckbox>
    <VegaCheckbox
      identifier="orange"
      size="small"
    >
      Orange
    </VegaCheckbox>
  </VegaCheckboxGroup>
</template>

// angular-demo/src/components/checkbox/examples/checkbox-group/checkbox-group.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-checkbox-group",
  templateUrl: "./checkbox-group.component.html",
  styleUrls: ["./checkbox-group.component.scss"]
})
export class CheckboxGroupComponent {}

<vega-checkbox-group
  [vegaFlexProp]="{ gap: 'size-12', direction: 'col' }"
  [value]="['apple', 'banana']"
>
  <vega-checkbox
    identifier="apple"
    size="small"
  >
    Apple
  </vega-checkbox>
  <vega-checkbox
    identifier="banana"
    size="small"
  >
    Banana
  </vega-checkbox>
  <vega-checkbox
    identifier="orange"
    size="small"
  >
    Orange
  </vega-checkbox>
</vega-checkbox-group>
