// react-demo/src/components/table/examples/table-with-clickable-row.jsx
import { useRef, useState } from "react";
import { VegaTable, VegaFlex } from "@heartlandone/vega-react";

const App = () => {
  const table = useRef();
  const [clickedRowRecord, setClickedRowRecord] = useState(null);
  const onRowClick = (e) => {
    setClickedRowRecord(e.detail);
  };

  return (
    <VegaFlex direction={`col`}>
      <VegaTable
        ref={table}
        rowClickable={true}
        columns={[
          {
            label: "Date",
            prop: "date",
          },
          {
            label: "Amount",
            prop: "amount",
          },
          {
            label: "Balance",
            prop: "balance",
          },
        ]}
        dataSource={[
          {
            key: "1",
            date: "01/01/2022",
            amount: 100,
            balance: "$100",
            status: "In Progress",
          },
          {
            key: "2",
            date: "01/02/2022",
            amount: 300,
            balance: "$200",
            status: "In Progress",
          },
          {
            key: "3",
            date: "01/03/2022",
            amount: 400,
            balance: "$300",
            status: "Not Started",
          },
          {
            key: "4",
            date: "01/04/2022",
            amount: 200,
            balance: "$400",
            status: "Pending",
          },
        ]}
        onVegaRowClick={onRowClick}
      />
      <div className={`v-bg-primary v-text-primary`}>
        <p className={`v-font-h4`}>Try to click a row</p>
        {clickedRowRecord && (
          <div>
            <label className={`v-font-field-label`}>Clicked Row Record:</label>
            <p className={`v-font-p2-short v-text-primary`}>
              {JSON.stringify(clickedRowRecord.record)}
            </p>
            <label className={`v-font-field-label`}>Clicked Row Index:</label>
            <p className={`v-font-p2-short v-text-primary`}>
              {clickedRowRecord.index}
            </p>
          </div>
        )}
      </div>
    </VegaFlex>
  );
};
export default App;

// angular-demo/src/components/table/examples/table-with-clickable-row/table-with-clickable-row.component.ts
import { Component } from "@angular/core"
export interface tableColumnsType {
  label: string
  prop: string
}
export interface dataSourceType {
  key: string
  balance: string
  date: string
  amount: number
  status: string
  name?: string
}
@Component({
  selector: "app-table-with-clickable-row",
  templateUrl: "./table-with-clickable-row.component.html",
  styleUrls: ["./table-with-clickable-row.component.scss"]
})
export class TableWithClickableRowComponent {
  clickedRowRecord = null
  columns: tableColumnsType[] = [
    {
      label: "Date",
      prop: "date"
    },
    {
      label: "Amount",
      prop: "amount"
    },
    {
      label: "Balance",
      prop: "balance"
    }
  ]
  dataSource: dataSourceType[] = [
    {
      key: "1",
      date: "01/01/2022",
      amount: 100,
      balance: "$100",
      status: "In Progress"
    },
    {
      key: "2",
      date: "01/02/2022",
      amount: 300,
      balance: "$200",
      status: "In Progress"
    },
    {
      key: "3",
      date: "01/03/2022",
      amount: 400,
      balance: "$300",
      status: "Not Started"
    },
    {
      key: "4",
      date: "01/04/2022",
      amount: 200,
      balance: "$400",
      status: "Pending"
    }
  ]
  stringifyClickedRowRecord(data: any) {
    return JSON.stringify(data.record)
  }
  clickedRecordRowIndex(data: any) {
    return JSON.stringify(data.index)
  }
  onRowClick(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    this.clickedRowRecord = customEvent.detail
  }
}

<vega-flex direction="col">
  <vega-table
    [rowClickable]="true"
    [columns]="columns"
    [dataSource]="dataSource"
    (vegaRowClick)="onRowClick($event)"
  />
  <div class="v-bg-primary v-text-primary">
    <p class="v-font-h6 v-mt-size-12">Try to click a row</p>

    <div *ngIf="clickedRowRecord">
      <label class="v-font-field-label">Clicked Row Record:</label>
      <p class="v-font-p2-short v-text-primary">
        {{ stringifyClickedRowRecord(clickedRowRecord) }}
      </p>
      <label class="v-font-field-label">Clicked Row Index:</label>
      <p class="v-font-p2-short v-text-primary">
        {{ clickedRecordRowIndex(clickedRowRecord) }}
      </p>
    </div>
  </div>
</vega-flex>
