// angular-demo/src/components/pagination/examples/pagination-with-ordering/pagination-with-ordering.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-pagination-with-ordering",
  templateUrl: "./pagination-with-ordering.component.html",
  styleUrls: ["./pagination-with-ordering.component.scss"]
})
export class PaginationWithOrderingComponent {}

<vega-pagination
  [current]="1"
  [pageSize]="10"
  [total]="100"
  [extensions]="[['pageSizeSelector'], ['pageSelector'], ['goTo']]"
/>

// react-demo/src/components/pagination/examples/pagination-with-ordering.jsx
import { useRef, useEffect } from "react";
import { VegaPagination } from "@heartlandone/vega-react";

const App = () => {
  const recordsPagination = useRef();
  useEffect(() => {
    recordsPagination.current.extensions = [
      ["pageSizeSelector"],
      ["pageSelector"],
      ["goTo"],
    ];
  });
  return (
    <VegaPagination
      ref={recordsPagination}
      current={1}
      pageSize={10}
      total={100}
    />
  );
};
export default App;
