// angular-demo/src/components/pagination/examples/pagination-with-variable-item-number-display/pagination-with-variable-item-number-display.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-pagination-with-variable-item-number-display",
  templateUrl: "./pagination-with-variable-item-number-display.component.html",
  styleUrls: ["./pagination-with-variable-item-number-display.component.scss"]
})
export class PaginationWithVariableItemNumberDisplayComponent {}

<vega-pagination
  [current]="1"
  [pageSize]="10"
  [total]="100"
  [extensions]="[['pageSizeSelector'], ['pageSelector', 'goTo']]"
/>

// react-demo/src/components/pagination/examples/pagination-with-variable-item-number-display.jsx
import { useRef, useEffect } from "react";
import { VegaPagination } from "@heartlandone/vega-react";

const App = () => {
  const recordsPagination = useRef();
  useEffect(() => {
    recordsPagination.current.extensions = [
      ["pageSizeSelector"],
      ["pageSelector", "goTo"],
    ];
  });
  return (
    <VegaPagination
      ref={recordsPagination}
      current={1}
      pageSize={10}
      total={100}
    />
  );
};
export default App;
