// angular-demo/src/components/pagination/examples/pagination-combined-example/pagination-combined-example.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-pagination-combined-example",
  templateUrl: "./pagination-combined-example.component.html",
  styleUrls: ["./pagination-combined-example.component.scss"]
})
export class PaginationCombinedExampleComponent {}

<vega-pagination
  [current]="1"
  [pageSize]="10"
  [total]="100"
  [extensions]="[
    ['currentPageLabel', 'pageSizeSelector'],
    ['pageSelector', 'goTo']
  ]"
/>

// react-demo/src/components/pagination/examples/pagination-combined-example.jsx
import { useRef, useEffect } from "react";
import { VegaPagination } from "@heartlandone/vega-react";

const App = () => {
  const recordsPagination = useRef();
  useEffect(() => {
    recordsPagination.current.extensions = [
      ["currentPageLabel", "pageSizeSelector"],
      ["pageSelector", "goTo"],
    ];
  });
  return (
    <VegaPagination
      ref={recordsPagination}
      current={1}
      pageSize={10}
      total={100}
    />
  );
};
export default App;
