// vue-demo/src/components/flex/examples/flex-with-different-width.vue
<script>
import { VegaFlex } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaFlex }
}
</script>
<template>
  <VegaFlex gap="size-8">
    <div
      class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8 v-w-size-40 v-min-w-min vega-flex-shrink-0"
    >
      Child Item 1
    </div>
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8 v-p-size-8">
      Child Item 2
    </div>
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8 v-p-size-8">
      Child Item 3
    </div>
  </VegaFlex>
</template>

// react-demo/src/components/flex/examples/flex-with-different-width.jsx
import { VegaFlex } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaFlex gap={`size-8`}>
      <div
        className={`v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8 v-w-size-40 v-min-w-min vega-flex-shrink-0`}
      >
        Child Item 1
      </div>
      <div
        className={`v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8 v-p-size-8`}
      >
        Child Item 2
      </div>
      <div
        className={`v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8 v-p-size-8`}
      >
        Child Item 3
      </div>
    </VegaFlex>
  );
};
export default App;
