// vue-demo/src/components/button/examples/button-secondary-variant.vue
<script>
import { VegaButton } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaButton },
  methods: {
    onClick() {}
  }
}
</script>

<template>
  <VegaButton variant="secondary" :disabled="false" @vegaclick="onClick"> Checkout </VegaButton>
</template>

// angular-demo/src/components/button/examples/button-secondary-variant/button-secondary-variant.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-button-secondary-variant",
  templateUrl: "./button-secondary-variant.component.html",
  styleUrls: ["./button-secondary-variant.component.scss"]
})
export class ButtonSecondaryVariantComponent {
  onClick(e: Event) {}
}

<vega-button
  variant="secondary"
  disabled="false"
  (vegaClick)="onClick($event)"
>
  Checkout
</vega-button>
