// vue-demo/src/components/modal/examples/modal.vue
<script>
import { VegaModal, VegaFlex, VegaButton } from "@heartlandone/vega-vue"

export default {
  data() {
    return {
      isOpen: false
    }
  },
  components: { VegaModal, VegaFlex, VegaButton },
  methods: {
    openModal() {
      this.isOpen = true
    },
    closeModal() {
      this.isOpen = false
    }
  }
}
</script>
<template>
  <VegaFlex direction="col">
    <VegaModal
      :size="400"
      backdrop="static"
      :open="isOpen"
      @vegaclose="closeModal"
    >
      <p class="v-font-p2-short v-text-primary v-mb-size-24">
        This content will appear in the modal.
      </p>

      <div>
        <VegaButton @vegaclick="closeModal">Close</VegaButton>
      </div>
    </VegaModal>
    <VegaButton @vegaclick="openModal">Launch modal</VegaButton>
  </VegaFlex>
</template>

// react-demo/src/components/modal/examples/modal.jsx
import { useState } from "react";
import { VegaModal, VegaFlex, VegaButton } from "@heartlandone/vega-react";

const App = () => {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <VegaFlex direction={`col`}>
      <VegaModal
        size={400}
        backdrop={`static`}
        open={isOpen}
        onVegaClose={() => setIsOpen(false)}
      >
        <p className={`v-font-p2-short v-text-primary`}>
          This content will appear in the modal.
        </p>

        <div>
          <VegaButton onVegaClick={() => setIsOpen(false)}>Close</VegaButton>
        </div>
      </VegaModal>
      <VegaButton onVegaClick={() => setIsOpen(true)}>Launch modal</VegaButton>
    </VegaFlex>
  );
};
export default App;
