// angular-demo/src/components/date-picker/examples/date-picker-with-range-with-min-max-date/date-picker-with-range-with-min-max-date.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-date-picker-with-range-with-min-max-date",
  templateUrl: "./date-picker-with-range-with-min-max-date.component.html",
  styleUrls: ["./date-picker-with-range-with-min-max-date.component.scss"]
})
export class DatePickerWithRangeWithMinMaxDateComponent {}

<vega-date-picker
  label="Min & Max Date Range"
  mode="range"
  max-date="05/20/2022"
  min-date="05/10/2022"
/>

// vue-demo/src/components/date-picker/examples/date-picker-with-range-with-min-max-date.vue
<script>
import { VegaDatePicker } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaDatePicker }
}
</script>
<template>
  <VegaDatePicker
    label="Min & Max Date Range"
    mode="range"
    max-date="05/20/2022"
    min-date="05/10/2022"
  />
</template>
