// react-demo/src/components/flex/examples/flex-combination.jsx
import { VegaFlex } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaFlex gap={`size-8`}>
      <div
        className={`v-bg-action v-font-p2-short v-text-inverted-primary v-w-size-40 v-bg-action vega-flex-shrink-0`}
      >
        Child Item 1
      </div>
      <div>
        <VegaFlex gap={`size-8`}>
          <div
            className={`v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8`}
          >
            Child Item 2
          </div>
          <div
            className={`v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8`}
          >
            Child Item 3
          </div>
          <div
            className={`v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8`}
          >
            Child Item 4
          </div>
        </VegaFlex>
      </div>
    </VegaFlex>
  );
};
export default App;

// angular-demo/src/components/flex/examples/flex-combination/flex-combination.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-flex-combination",
  templateUrl: "./flex-combination.component.html",
  styleUrls: ["./flex-combination.component.scss"]
})
export class FlexCombinationComponent {}

<vega-flex gap="size-8">
  <div
    class="v-bg-action v-font-p2-short v-text-inverted-primary v-w-size-40 v-bg-action vega-flex-shrink-0"
  >
    Child Item 1
  </div>
  <div>
    <vega-flex gap="size-8">
      <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 2</div>
      <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 3</div>
      <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 4</div>
    </vega-flex>
  </div>
</vega-flex>
