// vue-demo/src/components/carousel/examples/carousel-with-button-controls.vue
<script>
import { VegaCarousel, VegaCard, VegaFlex, VegaButtonCircle } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaCarousel, VegaCard, VegaFlex, VegaButtonCircle },
  methods: {
    goToNextPage() {
      this.$refs.carousel.$el.nextPage()
    },
    goToPreviousPage() {
      this.$refs.carousel.$el.prevPage()
    }
  }
}
</script>
<template>
  <VegaFlex direction="col">
    <VegaFlex gap="size-16">
      <VegaButtonCircle
        variant="secondary"
        size="default"
        icon="arrow-left"
        @vegaclick="goToPreviousPage"
      />
      <VegaButtonCircle
        variant="secondary"
        size="default"
        icon="arrow-right"
        @vegaclick="goToNextPage"
      />
    </VegaFlex>
    <VegaCarousel
      ref="carousel"
      per-page="1"
      spacing="size-32"
      show-slider="true"
    >
      <VegaCard
        shadow="shadow-card"
        background-color="bg-primary"
        padding="size-24"
      >
        <div class="v-text-primary v-font-p2-short">First page</div>
      </VegaCard>
      <VegaCard
        shadow="{`shadow-card`}"
        background-color="bg-primary"
        padding="size-24"
      >
        <div class="v-text-primary v-font-p2-short">Second page</div>
      </VegaCard>
      <VegaCard
        shadow="{`shadow-card`}"
        background-color="bg-primary"
        padding="size-24"
      >
        <div class="v-text-primary v-font-p2-short">Third page</div>
      </VegaCard>
    </VegaCarousel>
  </VegaFlex>
</template>

// angular-demo/src/components/carousel/examples/carousel-with-button-controls/carousel-with-button-controls.component.ts
import { Component, ViewChild } from "@angular/core"

@Component({
  selector: "app-carousel-with-button-controls",
  templateUrl: "./carousel-with-button-controls.component.html",
  styleUrls: ["./carousel-with-button-controls.component.scss"]
})
export class CarouselWithButtonControlsComponent {
  @ViewChild("carousel") carousel!: HTMLVegaCarouselElement
  goToPreviousPage(e: Event) {
    const previousButton: HTMLVegaButtonCircleElement = e.target as HTMLVegaButtonCircleElement
    this.carousel.prevPage()
  }
  goToNextPage(e: Event) {
    const nextButton: HTMLVegaButtonCircleElement = e.target as HTMLVegaButtonCircleElement
    this.carousel.nextPage()
  }
}

<vega-flex direction="col">
  <vega-flex gap="size-16">
    <vega-button-circle
      variant="secondary"
      size="default"
      icon="arrow-left"
      (vegaClick)="goToPreviousPage($event)"
    />
    <vega-button-circle
      variant="secondary"
      size="default"
      icon="arrow-right"
      (vegaClick)="goToNextPage($event)"
    />
  </vega-flex>
  <vega-carousel
    ngModel
    #carousel
    per-page="1"
    spacing="size-32"
    show-slider="true"
  >
    <vega-card
      shadow="shadow-card"
      background-color="bg-primary"
      padding="size-24"
    >
      <div class="v-text-primary v-font-p2-short">First page</div>
    </vega-card>
    <vega-card
      shadow="shadow-card"
      background-color="bg-primary"
      padding="size-24"
    >
      <div class="v-text-primary v-font-p2-short">Second page</div>
    </vega-card>
    <vega-card
      shadow="shadow-card"
      background-color="bg-primary"
      padding="size-24"
    >
      <div class="v-text-primary v-font-p2-short">Third page</div>
    </vega-card>
  </vega-carousel>
</vega-flex>
