// vue-demo/src/components/button/examples/button.vue
<script>
import { VegaButton } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaButton },
  methods: {
    onClick() {}
  }
}
</script>

<template>
  <VegaButton
    variant="primary"
    :disabled="false"
    @vegaclick="onClick"
  >
    Checkout
  </VegaButton>
</template>

// angular-demo/src/components/button/examples/button/button.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-button",
  templateUrl: "./button.component.html",
  styleUrls: ["./button.component.scss"]
})
export class ButtonComponent {
  onClick(e: Event) {}
}

<vega-button
  variant="primary"
  disabled="false"
  (vegaClick)="onClick($event)"
>
  Checkout
</vega-button>
