// vue-demo/src/components/accordion/examples/accordion-with-right-chevron.vue
<script>
import { VegaAccordion } from '@heartlandone/vega-vue'
export default {
  data() {
    return {}
  },
  components: { VegaAccordion }
}
</script>
<template>
  <VegaAccordion
    draws-background="false"
    accordion-title="Accordion Title"
    expand-icon-align="right"
    expand="false"
  >
    <!--eslint-disable-next-line vue/no-deprecated-slot-attribute-->
    <div slot="title">This is the title</div>
    <!--eslint-disable-next-line vue/no-deprecated-slot-attribute-->
    <div slot="content" class="v-font-p2-short v-text-primary">Accordion content</div>
  </VegaAccordion>
</template>

// react-demo/src/components/accordion/examples/accordion-with-right-chevron.js
import { VegaAccordion } from "@heartlandone/vega-react";

const App = () => (
  <VegaAccordion
    drawsBackground={false}
    title={`Accordion Title`}
    expandIconAlign={`right`}
    expand={false}
  >
    <div slot="title">This is the title</div>
    <div slot="content">
      <div className={`v-font-p2-short v-text-primary`}>Accordion content</div>
    </div>
  </VegaAccordion>
);

export default App;
