// react-demo/src/components/image-uploader/examples/image-uploader.jsx
import { useRef } from "react";
import { VegaImageUploader } from "@heartlandone/vega-react";

const App = () => {
  const uploader = useRef();
  const onChange = async (evt) => {
    if (evt.detail) {
      uploader.current.status = "uploading";
      setTimeout(() => {
        uploader.current.status = "done";
      }, 3000);
    }
  };
  return <VegaImageUploader ref={uploader} onVegaChange={onChange} />;
};
export default App;

// angular-demo/src/components/image-uploader/examples/image-uploader/image-uploader.component.ts
import { Component, ViewChild } from "@angular/core"

@Component({
  selector: "app-image-uploader",
  templateUrl: "./image-uploader.component.html",
  styleUrls: ["./image-uploader.component.scss"]
})
export class ImageUploaderComponent {
  @ViewChild("uploader") uploader!: HTMLVegaImageUploaderElement
  async onChange(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent

    if (customEvent.detail) {
      this.uploader.status = "uploading"
      setTimeout(() => {
        this.uploader.status = "done"
      }, 3000)
    }
  }
}

<vega-image-uploader
  ngModel
  #uploader
  (vegachange)="onChange($event)"
/>
