// react-demo/src/components/progress-tracker/examples/progress-tracker-horizontal.jsx
import { useRef, useEffect } from "react";
import { VegaProgressTracker } from "@heartlandone/vega-react";

const App = () => {
  const progressTracker = useRef();
  useEffect(() => {
    progressTracker.current.steps = [
      "Basic Information",
      "Contact Information",
      "Emergency Contact",
      "W-2 Forms",
    ];
  });
  return (
    <VegaProgressTracker
      ref={progressTracker}
      direction={`horizontal`}
      current={1}
    />
  );
};

export default App;

// angular-demo/src/components/progress-tracker/examples/progress-tracker-horizontal/progress-tracker-horizontal.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-progress-tracker-horizontal",
  templateUrl: "./progress-tracker-horizontal.component.html",
  styleUrls: ["./progress-tracker-horizontal.component.scss"]
})
export class ProgressTrackerHorizontalComponent {}

<vega-progress-tracker
  ref="progressTracker"
  direction="horizontal"
  [current]="1"
  [steps]="['Basic Information', 'Contact Information', 'Emergency Contact', 'W-2 Forms']"
/>
