// vue-demo/src/components/card/examples/card.vue
<script>
import { VegaCard } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaCard }
}
</script>
<template>
  <VegaCard
    padding="size-24"
    margin="size-8"
    variant="shadow"
    background-color="bg-primary"
  >
    <div className="v-font-p2-short v-text-primary">Content for the card goes here.</div>
  </VegaCard>
</template>

// react-demo/src/components/card/examples/card.jsx
import { VegaCard } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaCard
      padding={`size-24`}
      margin={`size-8`}
      variant={`shadow`}
      backgroundColor={`bg-primary`}
    >
      <div className={`v-font-p2-short v-text-primary`}>
        Content for the card goes here.
      </div>
    </VegaCard>
  );
};

export default App;
