// angular-demo/src/components/modal/examples/modal/modal.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-modal",
  templateUrl: "./modal.component.html",
  styleUrls: ["./modal.component.scss"]
})
export class ModalComponent {
  isOpen = false

  openModal(e: Event) {
    this.isOpen = true
  }
  closeModal(e: Event) {
    this.isOpen = false
  }
}

<vega-flex direction="col">
  <vega-modal
    [size]="400"
    backdrop="static"
    [open]="isOpen"
    (vegaClose)="closeModal($event)"
  >
    <p class="v-font-p2-short v-text-primary v-mb-size-24">
      This content will appear in the modal.
    </p>
    <div>
      <vega-button (vegaClick)="closeModal($event)">Close</vega-button>
    </div>
  </vega-modal>
  <vega-button (vegaClick)="openModal($event)">Launch modal</vega-button>
</vega-flex>

// vue-demo/src/components/modal/examples/modal.vue
<script>
import { VegaModal, VegaFlex, VegaButton } from "@heartlandone/vega-vue"

export default {
  data() {
    return {
      isOpen: false
    }
  },
  components: { VegaModal, VegaFlex, VegaButton },
  methods: {
    openModal() {
      this.isOpen = true
    },
    closeModal() {
      this.isOpen = false
    }
  }
}
</script>
<template>
  <VegaFlex direction="col">
    <VegaModal
      :size="400"
      backdrop="static"
      :open="isOpen"
      @vegaclose="closeModal"
    >
      <p class="v-font-p2-short v-text-primary v-mb-size-24">
        This content will appear in the modal.
      </p>

      <div>
        <VegaButton @vegaclick="closeModal">Close</VegaButton>
      </div>
    </VegaModal>
    <VegaButton @vegaclick="openModal">Launch modal</VegaButton>
  </VegaFlex>
</template>
