// vue-demo/src/components/button-circle/examples/button-circle.vue
<script>
import { VegaButtonCircle } from '@heartlandone/vega-vue'
export default {
  data() {
    return {}
  },
  components: { VegaButtonCircle },
  methods: {
    onClick() {}
  }
}
</script>

<template>
  <VegaButtonCircle
    variant="primary"
    size="large"
    icon="hb-menu"
    label="This labels the button"
    @vegaclick="onClick"
  />
</template>

// angular-demo/src/components/button-circle/examples/button-circle/button-circle.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-button-circle",
  templateUrl: "./button-circle.component.html",
  styleUrls: ["./button-circle.component.scss"]
})
export class ButtonCircleComponent {
  onClick(e: Event) {}
}

<vega-button-circle
  variant="primary"
  size="large"
  icon="hb-menu"
  label="This labels the button"
  (vegaClick)="onClick($event)"
/>
