// react-demo/src/components/app-footer/examples/app-footer-with-additional-links.jsx
import { VegaAppFooter } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaAppFooter
      termOfUseLabel={`Terms of use`}
      privacyPolicyLabel={`Privacy Policy`}
      additionalLinks={[{ label: "Another Link", URL: "https://google.com" }]}
    />
  );
};

export default App;

// vue-demo/src/components/app-footer/examples/app-footer-with-additional-links.vue
<script>
import { VegaAppFooter } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaAppFooter }
}
</script>
<template>
  <VegaAppFooter
    ref="footer"
    term-of-use-label="Terms of use"
    privacy-policy-label="Privacy Policy"
    :additional-links="[
      {
        label: 'Another Link',
        URL: 'https://google.com'
      }
    ]"
  />
</template>
