// angular-demo/src/components/app-footer/examples/app-footer-with-additional-links/app-footer-with-additional-links.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-app-footer-with-additional-links",
  templateUrl: "./app-footer-with-additional-links.component.html",
  styleUrls: ["./app-footer-with-additional-links.component.scss"]
})
export class AppFooterWithAdditionalLinksComponent {}

<vega-app-footer
  ref="footer"
  term-of-use-label="Terms of use"
  privacy-policy-label="Privacy Policy"
  [additionalLinks]="[
    {
      label: 'Another Link',
      URL: 'https://google.com'
    }
  ]"
/>

// vue-demo/src/components/app-footer/examples/app-footer-with-additional-links.vue
<script>
import { VegaAppFooter } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaAppFooter }
}
</script>
<template>
  <VegaAppFooter
    ref="footer"
    term-of-use-label="Terms of use"
    privacy-policy-label="Privacy Policy"
    :additional-links="[
      {
        label: 'Another Link',
        URL: 'https://google.com'
      }
    ]"
  />
</template>
