// vue-demo/src/components/grid/examples/grid.vue
<script>
import { VegaGrid } from "@heartlandone/vega-vue"
export default {
  data() {
    return {}
  },
  components: { VegaGrid }
}
</script>
<template>
  <VegaGrid
    :column="4"
    :row="3"
    gap="size-16"
  >
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 1</div>
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 2</div>
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 3</div>
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 4</div>
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 5</div>
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 6</div>
  </VegaGrid>
</template>

// react-demo/src/components/grid/examples/grid.jsx
import { VegaGrid } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaGrid column={4} row={3} gap={`size-16`}>
      <div className="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">
        Child Item 1
      </div>
      <div className="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">
        Child Item 2
      </div>
      <div className="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">
        Child Item 3
      </div>
      <div className="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">
        Child Item 4
      </div>
      <div className="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">
        Child Item 5
      </div>
      <div className="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">
        Child Item 6
      </div>
    </VegaGrid>
  );
};

export default App;
