// vue-demo/src/components/progress-tracker/examples/progress-tracker.vue
<script>
import { VegaProgressTracker } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaProgressTracker },
  mounted() {
    this.$refs.progressTracker.$el.steps = [
      "Basic Information",
      "Contact Information",
      "Emergency Contact",
      "W-2 Forms"
    ]
  }
}
</script>
<template>
  <VegaProgressTracker
    ref="progressTracker"
    direction="vertical"
    :current="1"
  />
</template>

// react-demo/src/components/progress-tracker/examples/progress-tracker.jsx
import { useRef, useEffect } from "react";
import { VegaProgressTracker } from "@heartlandone/vega-react";

const App = () => {
  const progressTracker = useRef();
  useEffect(() => {
    progressTracker.current.steps = [
      "Basic Information",
      "Contact Information",
      "Emergency Contact",
      "W-2 Forms",
    ];
  });
  return (
    <VegaProgressTracker
      ref={progressTracker}
      direction={`vertical`}
      current={1}
    />
  );
};

export default App;
