// angular-demo/src/components/color-picker/examples/color-picker/color-picker.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-color-picker",
  templateUrl: "./color-picker.component.html",
  styleUrls: ["./color-picker.component.scss"]
})
export class ColorPickerComponent {
  color = "#73E6DC"
  onColorPickerChange(e: Event) {
    const colorPicker: HTMLVegaColorPickerElement = e.target as HTMLVegaColorPickerElement
    this.color = colorPicker.value
  }
}

<vega-flex direction="col">
  <vega-color-picker
    label="Choose a Color"
    [value]="color"
    [autoValidation]="true"
    hint="Select a color from the list"
    (vegaChange)="onColorPickerChange($event)"
  />
  <div
    [style]="{
      marginTop: '12px',
      borderRadius: '8px',
      width: '200px',
      height: '200px',
      backgroundColor: color
    }"
  ></div>
</vega-flex>

// react-demo/src/components/color-picker/examples/color-picker.jsx
import { useState } from "react";
import { VegaColorPicker, VegaFlex } from "@heartlandone/vega-react";

const App = () => {
  const [color, setColor] = useState("#73E6DC");
  const onColorPickerChange = (evt) => {
    setColor(evt.currentTarget.value);
  };
  return (
    <VegaFlex direction={`col`}>
      <VegaColorPicker
        label={`Choose a Color`}
        value={color}
        autoValidation={true}
        hint={`Select a color from the list`}
        onVegaChange={onColorPickerChange}
      />
      <div
        style={{
          marginTop: "12px",
          borderRadius: "8px",
          width: "200px",
          height: "200px",
          backgroundColor: color,
        }}
      />
    </VegaFlex>
  );
};

export default App;
