// angular-demo/src/components/input-credit-card/examples/input-credit-card/input-credit-card.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-input-credit-card",
  templateUrl: "./input-credit-card.component.html",
  styleUrls: ["./input-credit-card.component.scss"]
})
export class InputCreditCardComponent {}

<vega-form>
  <vega-input-credit-card
    class="v-mb-size-12"
    [hideCardNumberOnBlur]="true"
    value="4111 1111 1111 1111"
  />
  <vega-input-credit-card
    class="v-mb-size-12"
    value="5555 5555 5555 4444"
  />
  <vega-input-credit-card
    class="v-mb-size-12"
    value="6011 1111 1111 1117"
  />
  <vega-input-credit-card
    class="v-mb-size-12"
    value="3782 822463 10006"
  />
</vega-form>

// react-demo/src/components/input-credit-card/examples/input-credit-card.jsx
import { VegaForm, VegaInputCreditCard } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaForm>
      <VegaInputCreditCard
        className={`v-mb-size-12`}
        hideCardNumberOnBlur={true}
        value={`4111 1111 1111 1111`}
      />
      <VegaInputCreditCard
        className={`v-mb-size-12`}
        value={`5555 5555 5555 4444`}
      />
      <VegaInputCreditCard
        className={`v-mb-size-12`}
        value={`6011 1111 1111 1117`}
      />
      <VegaInputCreditCard
        className={`v-mb-size-12`}
        value={`3782 822463 10006`}
      />
    </VegaForm>
  );
};
export default App;
