// react-demo/src/components/page-notification/examples/page-notification.jsx
import { VegaFlex, VegaButton } from "@heartlandone/vega-react";

const App = () => {
  const openNotifyWithTitle = () => {
    window.VegaNotify.open({
      title: "Title",
      message:
        "This is the content of notification. This is the content of notification.This is the content of notification.This is the content of notification.",
    });
  };
  const openNotifyWithoutTitle = () => {
    window.VegaNotify.open({
      message: "No title notification",
    });
  };
  return (
    <VegaFlex gap={`size-16`}>
      <VegaButton onVegaClick={openNotifyWithTitle}>With title</VegaButton>
      <VegaButton variant={`secondary`} onVegaClick={openNotifyWithoutTitle}>
        No title
      </VegaButton>
    </VegaFlex>
  );
};

export default App;

// vue-demo/src/components/page-notification/examples/page-notification.vue
<script>
import { VegaFlex, VegaButton } from "@heartlandone/vega-vue"
export default {
  data() {
    return {}
  },
  components: { VegaFlex, VegaButton },
  methods: {
    openNotifyWithTitle() {
      window.VegaNotify.open({
        title: "Title",
        message:
          "This is the content of notification. This is the content of notification.This is the content of notification.This is the content of notification."
      })
    },
    openNotifyWithoutTitle() {
      window.VegaNotify.open({
        message: "No title notification"
      })
    }
  }
}
</script>
<template>
  <VegaFlex gap="size-16">
    <VegaButton @vegaclick="openNotifyWithTitle">With title</VegaButton>
    <VegaButton
      variant="secondary"
      @vegaclick="openNotifyWithoutTitle"
    >
      No title
    </VegaButton>
  </VegaFlex>
</template>
