// vue-demo/src/components/input/examples/input.vue
<script>
import { VegaInput } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaInput }
}
</script>
<template>
  <VegaInput
    name="phone"
    label="Phone number"
    value="(555) 555-5555"
    autocomplete="off"
    prefix-icon="mobile-phone"
    :required="true"
    :max-length="14"
    :auto-validation="true"
    :mask-config="{ type: 'phone' }"
    hint="Enter your telephone number"
    :show-clear-icon="true"
  />
</template>

// angular-demo/src/components/input/examples/input/input.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-input",
  templateUrl: "./input.component.html",
  styleUrls: ["./input.component.scss"]
})
export class InputComponent {}

<vega-input
  name="phone"
  label="Phone number"
  value="(555) 555-5555"
  autocomplete="off"
  prefix-icon="mobile-phone"
  [required]="true"
  [maxLength]="14"
  [autoValidation]="true"
  [maskConfig]="{ type: 'phone' }"
  hint="Enter your telephone number"
  [showClearIcon]="true"
/>
