// angular-demo/src/components/banner/examples/banner/banner.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-banner",
  templateUrl: "./banner.component.html",
  styleUrls: ["./banner.component.scss"]
})
export class BannerComponent {}

<vega-banner
  mode="inline"
  [source]="[
    {
      avatar: 'https://vega.hlprd.com/images/home/get-started.svg',
      headline: 'Congratulations! You have been pre-qualified for a $20,000 Loan.',
      description:
        'You can use the money to increase inventory, buy equipment, hire or pay employees, whatever you need to help your business grow and succeed.
There is no lengthy application, just a few clicks. Upon approval, you will receive funds in your account instantly.',
      ctaText: 'Learn More',
      ctaURL: 'https://www.google.com/',
      backgroundColor: '#CFCFCF',
      showCloseButton: true
    },
    {
      headline: 'Congratulations! You have been pre-qualified for a $20,000 Loan.',
      description:
        'You can use the money to increase inventory, buy equipment, hire or pay employees, whatever you need to help your business grow and succeed.
There is no lengthy application, just a few clicks. Upon approval, you will receive funds in your account instantly.',
      ctaText: 'Learn More',
      ctaURL: 'https://www.google.com/'
    }
  ]"
/>

// react-demo/src/components/banner/examples/banner.jsx
import { VegaBanner } from "@heartlandone/vega-react";

const App = () => {
  const source = [
    {
      avatar: "https://vega.hlprd.com/images/home/get-started.svg",
      headline:
        "Congratulations! You have been pre-qualified for a $20,000 Loan.",
      description: `You can use the money to increase inventory, buy equipment, hire or pay employees, whatever you need to help your business grow and succeed.
There is no lengthy application, just a few clicks. Upon approval, you’ll receive funds in your account instantly.`,
      ctaText: "Learn More",
      ctaURL: "https://www.google.com/",
      backgroundColor: "#CFCFCF",
      showCloseButton: true,
    },
    {
      headline:
        "Congratulations! You have been pre-qualified for a $20,000 Loan.",
      description: `You can use the money to increase inventory, buy equipment, hire or pay employees, whatever you need to help your business grow and succeed.
There is no lengthy application, just a few clicks. Upon approval, you’ll receive funds in your account instantly.`,
      ctaText: "Learn More",
      ctaURL: "https://www.google.com/",
    },
  ];
  return <VegaBanner mode={`inline`} source={source} />;
};

export default App;
