// angular-demo/src/components/tooltip/examples/tooltip/tooltip.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-tooltip",
  templateUrl: "./tooltip.component.html",
  styleUrls: ["./tooltip.component.scss"]
})
export class TooltipComponent {}

<vega-tooltip
  [size]="100"
  content="This is a tooltip"
  trigger="hover"
  placement="top"
>
  <vega-button>Hover Me</vega-button>
</vega-tooltip>

// react-demo/src/components/tooltip/examples/tooltip.jsx
import { VegaTooltip, VegaButton } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaTooltip
      size={100}
      content={`This is a tooltip`}
      trigger={`hover`}
      placement={`top`}
    >
      <VegaButton>Hover Me</VegaButton>
    </VegaTooltip>
  );
};
export default App;
