// react-demo/src/components/tooltip/examples/tooltip.jsx
import { VegaTooltip, VegaButton } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaTooltip
      size={100}
      content={`This is a tooltip`}
      trigger={`hover`}
      placement={`top`}
    >
      <VegaButton>Hover Me</VegaButton>
    </VegaTooltip>
  );
};
export default App;

// vue-demo/src/components/tooltip/examples/tooltip.vue
<script>
import { VegaTooltip, VegaButton } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaTooltip, VegaButton }
}
</script>
<template>
  <VegaTooltip
    :size="100"
    content="This is a tooltip"
    trigger="hover"
    placement="top"
  >
    <VegaButton>Hover Me</VegaButton>
  </VegaTooltip>
</template>
