// angular-demo/src/components/button/examples/button-small/button-small.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-button-small",
  templateUrl: "./button-small.component.html",
  styleUrls: ["./button-small.component.scss"]
})
export class ButtonSmallComponent {
  onClick(e: Event) {}
}

<vega-button
  variant="primary"
  disabled="false"
  (vegaClick)="onClick($event)"
  size="small"
>
  Checkout
</vega-button>

// vue-demo/src/components/button/examples/button-small.vue
<script>
import { VegaButton } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaButton },
  methods: {
    onClick() {}
  }
}
</script>

<template>
  <VegaButton variant="primary" :disabled="false" @vegaclick="onClick" size="small">
    Checkout
  </VegaButton>
</template>
