// vue-demo/src/components/date-picker/examples/date-picker-with-range.vue
<script>
import { VegaDatePicker } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaDatePicker }
}
</script>
<template>
  <VegaDatePicker
    label="Range mode"
    mode="range"
    size="small"
    format="MM/DD/YYYY"
    :clear-button="true"
    :allow-repick="true"
  />
</template>

// angular-demo/src/components/date-picker/examples/date-picker-with-range/date-picker-with-range.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-date-picker-with-range",
  templateUrl: "./date-picker-with-range.component.html",
  styleUrls: ["./date-picker-with-range.component.scss"]
})
export class DatePickerWithRangeComponent {}

<vega-date-picker
  label="Range mode"
  mode="range"
  size="small"
  format="MM/DD/YYYY"
  [clearButton]="true"
  [allowRepick]="true"
/>
