// angular-demo/src/components/form/examples/form/form.component.ts
import { Component, ViewChild } from "@angular/core"

@Component({
  selector: "app-form",
  templateUrl: "./form.component.html",
  styleUrls: ["./form.component.scss"]
})
export class FormComponent {
  @ViewChild("form") form!: HTMLVegaFormElement

  async getValue(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    window.alert(JSON.stringify(await this.form.getValue(), null, 2))
  }
  validate(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    this.form.valid()
  }
  reset(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    this.form.reset()
  }
}

<vega-form
  ngModel
  #form
  data-vega-form="form"
>
  <vega-flex
    direction="col"
    class="v-mb-size-12"
  >
    <vega-input
      data-vega-form="input"
      [min]="6"
      [value]="3"
      label="Min value is 6"
    ></vega-input>

    <vega-form data-vega-form="nestedForm">
      <vega-input
        data-vega-form="nestedInput"
        [max]="12"
        [value]="15"
        label="This is a nested form input"
      ></vega-input>
    </vega-form>
  </vega-flex>
  <vega-flex
    direction="row"
    gap="size-24"
  >
    <vega-button (vegaClick)="getValue($event)">Get Value</vega-button>
    <vega-button (vegaClick)="validate($event)">Validate</vega-button>
    <vega-button (vegaClick)="reset($event)">Reset</vega-button>
  </vega-flex>
</vega-form>

// react-demo/src/components/form/examples/form.jsx
import { useRef } from "react";
import {
  VegaForm,
  VegaInput,
  VegaFlex,
  VegaButton,
} from "@heartlandone/vega-react";

const App = () => {
  const vegaForm = useRef();

  const getValue = async () => {
    window.alert(JSON.stringify(await vegaForm.current.getValue(), null, 2));
  };

  const validate = () => {
    vegaForm.current.valid();
  };

  const reset = () => {
    vegaForm.current.reset();
  };

  return (
    <VegaForm data-vega-form={`form`} ref={vegaForm}>
      <VegaFlex direction={`col`} className={`v-mb-size-12`}>
        <VegaInput
          data-vega-form={`input`}
          min={6}
          value={3}
          label={`Min value is 6`}
        ></VegaInput>

        <VegaForm data-vega-form={`nestedForm`}>
          <VegaInput
            data-vega-form={`nestedInput`}
            max={12}
            value={15}
            label={`This is a nested form input`}
          ></VegaInput>
        </VegaForm>
      </VegaFlex>
      <VegaFlex direction={`row`} gap={`size-24`}>
        <VegaButton onVegaClick={getValue}>Get Value</VegaButton>
        <VegaButton onVegaClick={validate}>Validate</VegaButton>
        <VegaButton onVegaClick={reset}>Reset</VegaButton>
      </VegaFlex>
    </VegaForm>
  );
};

export default App;
