// vue-demo/src/components/accordion/examples/accordion-with-right-chevron.vue
<script>
import { VegaAccordion } from '@heartlandone/vega-vue'
export default {
  data() {
    return {}
  },
  components: { VegaAccordion }
}
</script>
<template>
  <VegaAccordion
    draws-background="false"
    accordion-title="Accordion Title"
    expand-icon-align="right"
    expand="false"
  >
    <!--eslint-disable-next-line vue/no-deprecated-slot-attribute-->
    <div slot="title">This is the title</div>
    <!--eslint-disable-next-line vue/no-deprecated-slot-attribute-->
    <div slot="content" class="v-font-p2-short v-text-primary">Accordion content</div>
  </VegaAccordion>
</template>

// angular-demo/src/components/accordion/examples/accordion-with-right-chevron/accordion-with-right-chevron.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-accordion-with-right-chevron",
  templateUrl: "./accordion-with-right-chevron.component.html",
  styleUrls: ["./accordion-with-right-chevron.component.scss"]
})
export class AccordionWithRightChevronComponent {}

<vega-accordion
  draws-background="false"
  accordion-title="Accordion Title"
  expand-icon-align="right"
  expand="false"
>
  <!--eslint-disable-next-line vue/no-deprecated-slot-attribute-->
  <div slot="title">This is the title</div>
  <!--eslint-disable-next-line vue/no-deprecated-slot-attribute-->
  <div
    slot="content"
    class="v-font-p2-short v-text-primary"
  >
    Accordion content
  </div>
</vega-accordion>
