// react-demo/src/components/combo-box/examples/combo-box-with-creatable-options.jsx
import { useRef } from "react";
import { VegaComboBox } from "@heartlandone/vega-react";

const App = () => {
  const comboBox = useRef();
  const onCreate = (evt) => {
    comboBox.current.source.push({ key: evt.detail, label: evt.detail });
    comboBox.current.value = [...comboBox.current.value, evt.detail];
  };
  return (
    <VegaComboBox
      ref={comboBox}
      label={`label text`}
      required={true}
      source={[
        { key: "key1", label: "option 1" },
        { key: "key2", label: "option 2" },
        { key: "key3", label: "option 3" },
      ]}
      vegaDropdownProps={{ dynamicOption: true }}
      onVegaCreate={onCreate}
    />
  );
};
export default App;

// vue-demo/src/components/combo-box/examples/combo-box-with-creatable-options.vue
<script>
import { VegaComboBox } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaComboBox },
  methods: {
    onCreate(evt) {
      this.$refs.comboBox.$el.source.push({ key: evt.detail, label: evt.detail })
      this.$refs.comboBox.$el.value = [...this.$refs.comboBox.$el.value, evt.detail]
    }
  }
}
</script>
<template>
  <VegaComboBox
    ref="comboBox"
    label="label text"
    :required="true"
    :source="[
      { key: 'key1', label: 'option 1' },
      { key: 'key2', label: 'option 2' },
      { key: 'key3', label: 'option 3' }
    ]"
    :vega-dropdown-props="{ dynamicOption: true }"
    @vegacreate="onCreate"
  />
</template>
