// angular-demo/src/components/popover/examples/popover/popover.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-popover",
  templateUrl: "./popover.component.html",
  styleUrls: ["./popover.component.scss"]
})
export class PopoverComponent {}

<vega-flex
  id="container"
  direction="col"
>
  <vega-popover
    [size]="200"
    placement="left"
    alignment="start"
    positionRelativeTo="#container"
  >
    <vega-button slot="popover-content">Click Me</vega-button>
    <div
      slot="popover"
      className="v-font-p2-short v-text-primary"
    >
      I am a popover
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    </div>
  </vega-popover>
</vega-flex>

// react-demo/src/components/popover/examples/popover.jsx
import { VegaPopover, VegaFlex, VegaButton } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaFlex id="container" direction={`col`}>
      <VegaPopover
        size={200}
        placement={`left`}
        alignment={`start`}
        positionRelativeTo={`#container`}
      >
        <VegaButton slot={`popover-content`}>Click Me</VegaButton>
        <div slot={`popover`} className={`v-font-p2-short v-text-primary`}>
          I am a popover
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
        </div>
      </VegaPopover>
    </VegaFlex>
  );
};
export default App;
