// angular-demo/src/components/dropdown/examples/dropdown-with-dynamic-searchable-menu/dropdown-with-dynamic-searchable-menu.component.ts
import { Component, ViewChild } from "@angular/core"

export interface SourceMapObject {
  [key: string]: {
    label: string
    key: string
    url: string
  }
}

@Component({
  selector: "app-dropdown-with-dynamic-searchable-menu",
  templateUrl: "./dropdown-with-dynamic-searchable-menu.component.html",
  styleUrls: ["./dropdown-with-dynamic-searchable-menu.component.scss"]
})
export class DropdownWithDynamicSearchableMenuComponent {
  @ViewChild("dropdown") dropdown!: HTMLVegaDropdownElement
  sourceMap: SourceMapObject = {
    google: {
      label: "Google",
      key: "google",
      url: "https://google.com"
    },
    vega: {
      label: "Vega",
      key: "vega",
      url: "https://vega.hlprd.com/"
    }
  }

  objectValues = Object.values

  onCreate(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    const value = customEvent.detail
    this.dropdown.source.push({ key: value, label: value })
    this.sourceMap[value] = {
      label: value,
      key: value,
      url: ""
    }
  }
  onLinkClick(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    const value = customEvent.detail
    window.open(this.sourceMap[value].url, "_blank")
  }
}

<vega-dropdown
  ngModel
  #dropdown
  [source]="objectValues(sourceMap)"
  (vegaDropdownClick)="onLinkClick($event)"
  [searchable]="true"
  [dynamicOption]="true"
  (vegaCreate)="onCreate($event)"
>
  <vega-button icon="hb-menu">Menu</vega-button>
</vega-dropdown>

// vue-demo/src/components/dropdown/examples/dropdown-with-dynamic-searchable-menu.vue
<script>
import { VegaDropdown, VegaButton } from "@heartlandone/vega-vue"

export default {
  data() {
    return {
      sourceMap: {
        google: {
          label: "Google",
          key: "google",
          url: "https://google.com",
          group: "links"
        },
        vega: {
          label: "Vega",
          key: "vega",
          url: "https://vega.hlprd.com/",
          group: "links"
        },
        option3: { label: "Option3", key: "option3", url: "#", group: "options" }
      }
    }
  },
  components: { VegaDropdown, VegaButton },
  methods: {
    onCreate(evt) {
      this.$refs.dropdown.$el.source.push({ key: evt.detail, label: evt.detail })
      this.$refs.dropdown.$el.value = [...this.$refs.dropdown.$el.value, evt.detail]
    },
    onLinkClick(evt) {
      window.open(this.sourceMap[evt.detail].url, "_blank")
    }
  }
}
</script>
<template>
  <VegaDropdown
    :source="Object.values(sourceMap)"
    @Vegadropdownclick="onLinkClick"
    :searchable="true"
    :dynamic-option="true"
    @vegacreate="onCreate"
  >
    <VegaButton icon="hb-menu">Menu</VegaButton>
  </VegaDropdown>
</template>
