// react-demo/src/components/flex/examples/flex.jsx
import { VegaFlex } from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaFlex gap={`size-8`}>
      <div
        className={`v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8`}
      >
        Child Item 1
      </div>
      <div
        className={`v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8`}
      >
        Child Item 2
      </div>
      <div
        className={`v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8`}
      >
        Child Item 3
      </div>
    </VegaFlex>
  );
};
export default App;

// vue-demo/src/components/flex/examples/flex.vue
<script>
import { VegaFlex } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaFlex }
}
</script>
<template>
  <VegaFlex gap="size-8">
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 1</div>
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 2</div>
    <div class="v-bg-action v-font-p2-short v-text-inverted-primary v-p-size-8">Child Item 3</div>
  </VegaFlex>
</template>
