// vue-demo/src/components/chip/examples/chip-with-border-and-responsive-size.vue
<script>
import { VegaChip } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaChip }
}
</script>
<template>
  <VegaChip
    text="Chip"
    variant="outlined"
    :size="{ default: 'extra-small', S: 'small', M: 'default', L: 'large' }"
  />
</template>

// angular-demo/src/components/chip/examples/chip-with-border-and-responsive-size/chip-with-border-and-responsive-size.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-chip-with-border-and-responsive-size",
  templateUrl: "./chip-with-border-and-responsive-size.component.html",
  styleUrls: ["./chip-with-border-and-responsive-size.component.scss"]
})
export class ChipWithBorderAndResponsiveSizeComponent {}

<vega-chip
  text="Chip"
  variant="outlined"
  [size]="{ default: 'extra-small', S: 'small', M: 'default', L: 'large' }"
/>
