// vue-demo/src/components/page-notification/examples/page-notification-types.vue
<script>
import { VegaFlex, VegaButton } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaFlex, VegaButton },
  methods: {
    openNotify(evt) {
      const button = evt.currentTarget
      const type = button.id
      window.VegaNotify.open({
        type: type,
        message: `${button.textContent.toUpperCase()}`
      })
    }
  }
}
</script>
<template>
  <VegaFlex
    gap="size-16"
    :direction="{ default: 'row', S: 'col', M: 'row' }"
  >
    <VegaButton
      id="warning"
      @vegaclick="openNotify"
      variant="secondary"
    >
      Warning
    </VegaButton>
    <VegaButton
      id="success"
      variant="secondary"
      @vegaclick="openNotify"
    >
      Success
    </VegaButton>
    <VegaButton
      id="error"
      variant="secondary"
      @vegaclick="openNotify"
    >
      Error
    </VegaButton>
    <VegaButton
      id="info"
      variant="secondary"
      @vegaclick="openNotify"
    >
      Info
    </VegaButton>
  </VegaFlex>
</template>

// angular-demo/src/components/page-notification/examples/page-notification-types/page-notification-types.component.ts
import { Component } from "@angular/core"
import { VegaNotify } from "@heartlandone/vega"
import { VegaPageNotificationTypes } from "@heartlandone/vega/dist/types/components/vega-page-notification/vega-page-notification"

@Component({
  selector: "app-page-notification-types",
  templateUrl: "./page-notification-types.component.html",
  styleUrls: ["./page-notification-types.component.scss"]
})
export class PageNotificationTypesComponent {
  openNotify(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    const button: HTMLVegaButtonElement = customEvent.target as HTMLVegaButtonElement

    const type = button.id
    const text = button.textContent as string
    const params = {
      type: type as VegaPageNotificationTypes,
      message: `${text.toUpperCase()}`
    }
    VegaNotify.open(params)
  }
}

<vega-flex
  gap="size-16"
  [direction]="{ default: 'row', S: 'col', M: 'row' }"
>
  <vega-button
    id="warning"
    (vegaClick)="openNotify($event)"
    variant="secondary"
  >
    Warning
  </vega-button>
  <vega-button
    id="success"
    variant="secondary"
    (vegaClick)="openNotify($event)"
  >
    Success
  </vega-button>
  <vega-button
    id="error"
    variant="secondary"
    (vegaClick)="openNotify($event)"
  >
    Error
  </vega-button>
  <vega-button
    id="info"
    variant="secondary"
    (vegaClick)="openNotify($event)"
  >
    Info
  </vega-button>
</vega-flex>
