// angular-demo/src/components/page-notification/examples/page-notification/page-notification.component.ts
import { Component } from "@angular/core"
import { VegaNotify } from "@heartlandone/vega"

@Component({
  selector: "app-page-notification",
  templateUrl: "./page-notification.component.html",
  styleUrls: ["./page-notification.component.scss"]
})
export class PageNotificationComponent {
  openNotifyWithTitle(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    VegaNotify.open({
      title: "Title",
      message:
        "This is the content of notification. This is the content of notification.This is the content of notification.This is the content of notification."
    })
  }
  openNotifyWithoutTitle(e: Event) {
    const customEvent: CustomEvent = e as CustomEvent
    VegaNotify.open({
      message: "No title notification"
    })
  }
}

<vega-flex gap="size-16">
  <vega-button (vegaClick)="openNotifyWithTitle($event)">With title</vega-button>
  <vega-button
    variant="secondary"
    (vegaClick)="openNotifyWithoutTitle($event)"
  >
    No title
  </vega-button>
</vega-flex>

// react-demo/src/components/page-notification/examples/page-notification.jsx
import { VegaFlex, VegaButton } from "@heartlandone/vega-react";

const App = () => {
  const openNotifyWithTitle = () => {
    window.VegaNotify.open({
      title: "Title",
      message:
        "This is the content of notification. This is the content of notification.This is the content of notification.This is the content of notification.",
    });
  };
  const openNotifyWithoutTitle = () => {
    window.VegaNotify.open({
      message: "No title notification",
    });
  };
  return (
    <VegaFlex gap={`size-16`}>
      <VegaButton onVegaClick={openNotifyWithTitle}>With title</VegaButton>
      <VegaButton variant={`secondary`} onVegaClick={openNotifyWithoutTitle}>
        No title
      </VegaButton>
    </VegaFlex>
  );
};

export default App;
