// vue-demo/src/components/radio/examples/radio.vue
<script>
import { VegaRadioGroup, VegaRadio } from "@heartlandone/vega-vue"

export default {
  data() {
    return {}
  },
  components: { VegaRadioGroup, VegaRadio },
  mounted() {}
}
</script>
<template>
  <VegaRadioGroup
    :vega-flex-prop="{
      gap: 'size-8',
      direction: 'col',
      breakpoint: 'None',
      alignItem: 'start',
      justifyContent: 'start',
      margin: 0
    }"
    ref="radioGroup"
    name="fruit"
    value="apple"
    label="Select a fruit"
  >
    <VegaRadio value="apple">Apple</VegaRadio>
    <VegaRadio value="orange">Orange</VegaRadio>
  </VegaRadioGroup>
</template>

// angular-demo/src/components/radio/examples/radio/radio.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-radio",
  templateUrl: "./radio.component.html",
  styleUrls: ["./radio.component.scss"]
})
export class RadioComponent {}

<vega-radio-group
  [vegaFlexProp]="{
    gap: 'size-8',
    direction: 'col',
    breakpoint: 'None',
    alignItem: 'start',
    justifyContent: 'start',
    margin: 0
  }"
  ref="radioGroup"
  name="fruit"
  value="apple"
  label="Select a fruit"
>
  <vega-radio value="apple">Apple</vega-radio>
  <vega-radio value="orange">Orange</vega-radio>
</vega-radio-group>
