// angular-demo/src/components/sidenav/examples/sidenav/sidenav.component.ts
import { Component } from "@angular/core"

@Component({
  selector: "app-sidenav",
  templateUrl: "./sidenav.component.html",
  styleUrls: ["./sidenav.component.scss"]
})
export class SidenavComponent {}

<vega-flex>
  <div data-shrink="0">
    <vega-sidenav
      footnote="Version 2.0.0"
      open-by-default="disableCollapse"
    >
      <vega-sidenav-link
        icon="hb-menu"
        url="#"
      >
        Company Name
      </vega-sidenav-link>
      <vega-sidenav-link
        icon="fas fa-shopping-bag fa-lg"
        url="#"
      >
        Order Equipment
      </vega-sidenav-link>
      <vega-sidenav-group
        icon="fas fa-file-alt fa-lg"
        label="Dashboard"
      >
        <vega-sidenav-link url="#">Form W-9</vega-sidenav-link>
        <vega-sidenav-link
          url="#"
          :selected="true"
        >
          Form W-8BEN
        </vega-sidenav-link>
        <vega-sidenav-link url="#">
          Very very very very very very very very long title
        </vega-sidenav-link>
      </vega-sidenav-group>
      <vega-sidenav-group
        icon="fas fa-user fa-lg"
        label="Main Heading"
      >
        <vega-sidenav-link url="#">Sub-Heading</vega-sidenav-link>
        <vega-sidenav-link url="#">Sub-Heading</vega-sidenav-link>
        <vega-sidenav-link url="#">Sub-Heading</vega-sidenav-link>
      </vega-sidenav-group>
      <vega-sidenav-link
        icon="fas fa-comment-dots fa-lg"
        url="#"
      >
        Support
      </vega-sidenav-link>
    </vega-sidenav>
  </div>
  <div><!-- Main Content --></div>
</vega-flex>

// react-demo/src/components/sidenav/examples/sidenav.jsx
import {
  VegaFlex,
  VegaSidenav,
  VegaSidenavGroup,
  VegaSidenavLink,
} from "@heartlandone/vega-react";

const App = () => {
  return (
    <VegaFlex>
      <div data-shrink="0">
        <VegaSidenav
          footnote={`Version 2.0.0`}
          openByDefault={`disableCollapse`}
        >
          <VegaSidenavLink icon={`hb-menu`} url="#">
            Company Name
          </VegaSidenavLink>
          <VegaSidenavLink icon={`fas fa-shopping-bag fa-lg`} url="#">
            Order Equipment
          </VegaSidenavLink>
          <VegaSidenavGroup icon={`fas fa-file-alt fa-lg`} label={`Dashboard`}>
            <VegaSidenavLink url="#">Form W-9</VegaSidenavLink>
            <VegaSidenavLink url="#" selected={true}>
              Form W-8BEN
            </VegaSidenavLink>
            <VegaSidenavLink url="#">
              Very very very very very very very very long title
            </VegaSidenavLink>
          </VegaSidenavGroup>
          <VegaSidenavGroup icon="fas fa-user fa-lg" label="Main Heading">
            <VegaSidenavLink url="#">Sub-Heading</VegaSidenavLink>
            <VegaSidenavLink url="#">Sub-Heading</VegaSidenavLink>
            <VegaSidenavLink url="#">Sub-Heading</VegaSidenavLink>
          </VegaSidenavGroup>
          <VegaSidenavLink icon={`fas fa-comment-dots fa-lg`} url="#">
            Support
          </VegaSidenavLink>
        </VegaSidenav>
      </div>
      <div>{/* Main Content */}</div>
    </VegaFlex>
  );
};

export default App;
