// react-demo/src/components/chip/examples/chip.jsx
import { useRef } from "react";
import { VegaChip } from "@heartlandone/vega-react";

const App = () => {
  const chip = useRef();
  const closeChip = () => {
    chip.current.remove();
  };
  return (
    <VegaChip
      ref={chip}
      text={`Chip`}
      clickable={true}
      showCloseIcon={true}
      onVegaClick={null}
      onVegaClose={closeChip}
    />
  );
};
export default App;

// vue-demo/src/components/chip/examples/chip.vue
<script>
import { VegaChip } from '@heartlandone/vega-vue'

export default {
  data() {
    return {}
  },
  components: { VegaChip },
  methods: {
    closeChip() {
      this.$refs.chip.$el.remove()
    }
  }
}
</script>
<template>
  <VegaChip
    ref="chip"
    text="Chip"
    :clickable="true"
    :show-close-icon="true"
    @vegaclick="null"
    @vegaclose="closeChip"
  />
</template>
